### ISSUE TITLE
Support setting power-on behavior for Hue lights

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1001]
Some hue lights support setting the power-on behavior from the [Hue Bluetooth-based app](https://play.google.com/store/apps/details?id=com.signify.hue.blue&hl=en_US&gl=US) (e.g. on Android). This is the only reason I actually use the app. The big downside of the app is that when you get a new phone you need to reset all Hue lights to be able to Bluetooth-pair them with the new phone. This will also require repairing the lights with Zigbee.

One light that I own has a documented way to set the desired power-on behavior:

https://www.zigbee2mqtt.io/devices/5062431P7.html#power-on-behavior

It would be great if this could be exposed via a state in ioBroker.

**Comment by arteck** [comment]
you can select this Device in exclude tab.. in adapter 1.4.4... check plz

**Comment by agross** [comment]
@arteck Sorry, I do not understand what you are trying to say.

**Comment by arteck** [comment]
no.... which version you use ??

**Comment by agross** [comment]
Latest.

**Comment by agross** [comment]
Not sure how the new tab relates to my request.

**Comment by arteck** [comment]
ohh sry.. i see now the bulb uses no exposes

![grafik](https://user-images.githubusercontent.com/6681528/108673877-b69c6380-74e4-11eb-905b-40cc617c05c8.png)

**Comment by asgothian** [comment]
> ohh sry.. i see now the bulb uses no exposes

It does use exposes. Their definition is hidden in „hue.light_onoff_brightness_ olortemp_colorxy“

A.

**Comment by asgothian** [comment]
> Not sure how the new tab relates to my request.

If you add the device to the exclude list you should get a larger st of states defined by the Zigbee-Herdsman-Converters, which may include the desired function.

A.

**Comment by agross** [comment]
![image](https://user-images.githubusercontent.com/16245/108708117-4bb55180-7511-11eb-9093-ed14e56f7e92.png)

This is what it looks like after excluding the light. I don't see the `set` part that is required as per the docs.

I also wonder why excluding things makes them more versatile. Can you explain?

**Comment by asgothian** [comment]
> I also wonder why excluding things makes them more versatile. Can you explain?

The explanation for this needs a bit more background.

Initially, the zigbee-herdsman-converters defined devices and converters which translate messages sent from the client application (zigbee2mqtt or ioBroker.zigbee) into zigbee messages and vice versa. These converters were (and still are) closely linked to the zigbee hardware messages, and do not include information as to what data is expected and which function is linked to the specific message. 
For ioBroker.zigbee, this information was (and is) provided via the device definition in devices.js and states.js.

Over the last few months, the developers of the zigbee-herdsman-converters have started so called 'exposes', where the converters expose certain functions in a standardized fashion to the client application. With these exposes, the client application can set up a representation of the device and control its functions.

Starting with Version 1.4.1, the zigbee Adapter also learned to use these exposes to define device behavior. For compatibility reason, priority is given to the device description in devices.js and states.js for all devices which are defined within the adapter code, while new devices are implemented only if the exposes do not allow for an adequate representation of the device. Notable examples for this are the Lidl Christmas lights, or the pvto.switch configurable device.

In order to offer a choice to users if to stick to the device definition in the adapter code or to use the exposes from the zigbee herdsman converters @arteck implemented the exclude list. Any device entered into this list will use the exposes even if a device definition is present in the adapter code. For devices which were implemented long ago this can lead to more states being offered when exposes are used.

A.

**Comment by asgothian** [comment]
Please test the current 1.4.5 GitHub version of the adapter. It includes a scriptable function which should allow for you to set the desired states on the bulb.

Use of the function is through JS or Blockly:
```
sendTo("zigbee.0", "SendToDevice", {
   "device": 'your device id here (without 0x)',
   "payload": 'the payload as listed on zigbee2mqtt here',
   "endpoint": 'Optional for multi-endpoint devices',
   "options": 'optional for specific commands'
}, function(result) {
   if (result.success) then console.log("success") else console.log("Error " + console.error);
});
```
<img width="409" alt="Screen Shot 2021-03-13 at 12 27 01 " src="https://user-images.githubusercontent.com/45667167/111028516-6a638580-83f7-11eb-9e4d-dcaa62fea038.png">

**Comment by agross** [comment]
Does the device need to be "excluded" for this to work?

**Comment by asgothian** [comment]
No, it should work independent of the method of integration

**Comment by agross** [comment]
Tried it [with this script](https://github.com/agross/iobroker-scripts/blob/0f1ecb1a13c0af6b1e6096aa84a4c8f195995705/0/Automation/Oneshot/Zigbee_Power_On_Behavior.ts) which handles all my Zigbee lights.

One thing that does not seem to work is error handling. Either the `sendTo` returns successfully or in case of errors, the callback is never called (but the Zigbee adapter logs an error).

```
info: javascript.0 (7956) script.js.Automation.Oneshot.Zigbee_Power_On_Behavior: Configured zigbee.1.680ae2fffea24937 (Office #1 TRADFRI bulb E27 WS opal 1000lm)
info: javascript.0 (7956) script.js.Automation.Oneshot.Zigbee_Power_On_Behavior: Configured zigbee.1.680ae2fffea72a25 (Utility Room TRADFRI bulb E27 WS opal 1000lm)
error: zigbee.1 (3841) No converter available for '' with key 'hue_power_on_behavior'
error: zigbee.1 (3841) No converter available for '' with key 'hue_power_on_behavior'
error: zigbee.1 (3841) No converter available for '' with key 'hue_power_on_behavior'
```

**Comment by agross** [comment]
After some tests I can report that setting `hue_power_on_behavior` works! 👍

**Comment by mafof** [comment]
You can use the developer tab in the zigbee driver, and set the following parameters there:
Endpoint - "11"
Cluster ID -"genOnOff (6)"
Command type -"Foundation"
Command - "write (2)"
Attribute ID - "startUpOnOff (16387, type 48)"
And also set either 1 or 0 in Value.
As a result, the received results should display the inscription " SUCCESS undefined"

**Comment by agross** [comment]
Thank you, but unfortunately this variant is not scriptable.

**Comment by asgothian** [comment]
Actually, this variant is also scriptable. What you need to do:

- set up the command in the developer tab
- check the "expert mode" checkbox
- copy the JSON from the expert settings.
- use the following JS (it is not easily available in Blockly)
```
sendTo("zigbee.0", "SendToDevice", <payload> , function(result) {
   if (result.success) then console.log("success") else console.log("Error " + console.error);
});
```
Keep in mind that <payload> needs to be the entry from the expert tab.

A.

**Comment by agross** [comment]
Ok, maybe then it is scriptable. But I guess errors won't be handled as well (see above). I find the `SendToDevice` variant you suggested earlier less cryptic than sending magic values that are not part of zigbee2mqtt's documentation.

**Comment by asgothian** [comment]
Agreed - that is exactly the reason this function was implemented. I just wanted to clarify that it is possible to send messages to a device even if there is no respective support built into the current zigbee-herdsman-converters.

A>

**Comment by agross** [comment]
@asgothian Now that the issue is closed, did anything change regarding error handling? https://github.com/ioBroker/ioBroker.zigbee/issues/1001#issuecomment-798898707

**Comment by asgothian** [comment]
> @asgothian Now that the issue is closed, did anything change regarding error handling? [#1001 (comment)](https://github.com/ioBroker/ioBroker.zigbee/issues/1001#issuecomment-798898707)

No. The error handling is as it is supposed to and will stay that way. It is neither sensible nor possible to block the error message for a missing converter from being posted to the log. The function itself does not get a notification that the payload was not understood by the herdsman, so it will only return an error when the sending itself fails. As such, it is working as intended.
