### ISSUE TITLE
Version 1.4.4 - Bug mit Hue E14 White & Color (Brightness -> State)

### ISSUE THREAD

**Issue by Animizio** [ioBroker/ioBroker.zigbee#1002]
Hallo,

ich habe einen Fehler in Version 1.4.4 gefunden. Dieser tritt in Version 1.4.1 NOCH NICHT auf.

Fehler:
Veränderung der Werte von "Brightness" senden kein Signal an "State". Somit wird der State nicht mehr auf True/False getriggert.
State anpingen über Script funktioniert einwandfrei, betreffen daher den Brightness-Wert -> State-Wert und Fehler sind bisher nur mit genannter Lampe bekannt.

modelZigbee: LCT012
model: 9290012573A
Hue white and color ambiance E14

Bei weiteren Fragen oder Informationen stehe ich gerne zur Verfügung.

**Comment by asgothian** [comment]
Thank you for reporting this. This seems to be a bug in the exposes. I will need to investigate this.

**Comment by asgothian** [comment]
@arteck, @kirovilya: This bug is connected to exposes. This is the current situation:
When a light is defined in devices.js, we add either linkedStates (for most Ikea lamps for example) or         syncStates (most Hue lamps seem to have this). With this entry, the lights will update the "state" when brightness changes turns the light on or off. If a light is using exposes natively (there is no entry in states.js for the device) neither linkedStates nor syncStates are set. If a device uses states from exposes through the "exclude" option, the linkedStates / syncStates from devices.js is still active.

The question is how to deal with this. I see 4 Options, but do not know enough about the difference between linkedStates and syncStates to be sure that all of them are viable:


1. add         syncStates: [sync.brightness] to the device definition from exposes for light devices, which (tested with the 9290012573A) will cause the _state_ to turn on when _brightness_ is changed to a non-zero value, but will not turn _state_ off when _brightness_ is set to 0
2. add          linkedStates: [comb.brightnessAndState] to the device definition from exposes for light devices, which (tested with Ikea LED1649C5 and 9290012573A) which will ensure that _state_ will change when _brightness_ is changed (to on with a non-0 value, to off with a 0 value)
3. add a forced configure to all lights so that they report the _state_ and _brightness_ changes when the light changes them for any reason (this would also fix the group issue, but may not be supported on all light devices) 
4. do nothing and declare this as the new 'desired' functionality (the worst option in my eyes)

**Comment by kirovilya** [comment]
Difference between linkedStates and syncStates:
syncStates - sets the second state after the execution of the action (if the brightness is changed to 0 - set that the state is off), an additional command is not sent
linkedStates - supplements the set of changes (if the brightness is changed to 0 - additionally change the state to off), an additional command is sent

An additional option `meta: {turnsOffAtBrightness1: true}` began to appear in the description of some devices.
It performs state changes and sends commands. perhaps for the devices we need, it's enough to add this to the description and not make a link and sync on out side.

**Comment by asgothian** [comment]
> An additional option `meta: {turnsOffAtBrightness1: true}` began to appear in the description of some devices.
> It performs state changes and sends commands. perhaps for the devices we need, it's enough to add this to the description and not make a link and sync on out side.

That sounds interesting. Will setting that also set the state to true when brightness is changed to a nonzero value ? If so, adding that meta to all lights would be the easiest solution.

A.

**Comment by Animizio** [comment]
Hey,
sadly this bug is still happening on latest update i tried (now 1.5.3).
I will need to stay on 1.4.1 till the bug is fixed, because its the latest working version for this light bulb!
Please get a fix around. If you need testing, more informations etc. I'm trying my best to help.

**Comment by Animizio** [comment]
*push*
No fix yet. Still need to stay on Zigbee Adapter 1.4.1 till it is fixed.

**Comment by Animizio** [comment]
push
