### ISSUE TITLE
Invalid IDs accepted by the adapter

### ISSUE THREAD

**Issue by lansester** [ioBroker/ioBroker.zigbee#1010]
Hello!

I was recently having quite some trouble with a massive change in the allowed range of PanIDs.
Since the latest version only a quite limited range of PanIDs is still alllowed.  approx. 1-65k
Before a much wider range was allowed and working perfectly fine with the devices.

The problem is, that the adapter does not provide any hint in the description next to the PanID field about the allowed range of IDs and does even accept invalid IDs and then crashes with an error message.
The adapter shall definitvely check and confirm or decline any entered ID or Key instead of crashing or loosing the links because of an entered invalid ID.

Thanks!

**Comment by asgothian** [comment]
This is not any function of the Adapter. This is a function which was updated in the underlying zigbee library, which
- reports the error to back to the Adapter
- Refuses to start the Adapter if the pan id does not fit the current range.

the errors you saw were caused by automatic restart attempts and errors from the zigbee-herdsman-converters which does not properly handle the error.

I am afraid you have exactly three options:
- change the pan id and pair all devices with a correct pan I’d
- Downgrade the Adapter to the last known working version. Note that this change was introduced sometime between 1.3.1 and 1.4.4
- Patch the zigbee-Herdsman Library to ignore the Check.


A.

**Comment by asgothian** [comment]
Duplicate of #1000
