### ISSUE TITLE
DEBOUNCE option in Adapter

### ISSUE THREAD

**Issue by xlklwr** [ioBroker/ioBroker.zigbee#1012]
Is it possible to add the debounce option (https://www.zigbee2mqtt.io/information/configuration.html#all-devices --> debounce) for single devices to the adaptor? I having issues with the Xiaomi RTCGQ11LM as it submits occupacy and illuminance at the same time, so the occupacy is not updated it iobroker (the timestamp and value for illu changes, but not for occupacy) so after some trial and error i believe that is the issue: https://www.gitmemory.com/issue/Koenkk/zigbee2mqtt/4859/721282333

**Comment by asgothian** [comment]
I believe there was a change in the Adapter a while back which activated the debounce by default for this device.

Which adapter version are you running ?

A.

**Comment by xlklwr** [comment]
Hi Asgothian,

V1.4.4. According my research the illue value is only transmitted when a motion is detected. In my datapoints i can see on the timestamp of illu that it has been updated when i passed the senor, the status or timestamp of occupacy does not change.

**Comment by asgothian** [comment]
I verified behavior of the  RTCGQ11LM with its messages for occupancy and illuminance. The underlying issue is confirmed fixed in the zigbee-herdsman-converters for this device in a way that any update for illuminance will always also update occupancy. This has nothing to do with the debounce issue, as the main issue is that the herdsman itself might miss occupancy messages from the device if they are sent too quickly after illuminance messages.

As far as implementing the debounce option - this is definitely a possibility, although i see little use for it as it will delay reaction to the message by approx. 1.5x the debounce time. Given that this is entered in seconds. I also see little need for it as the zigbee Adapter can easily deal with fast paced messages coming from the herdsman.

A.
