### ISSUE TITLE
bitronhome 902010/23

### ISSUE THREAD

**Issue by Schmusekater76** [ioBroker/ioBroker.zigbee#1025]
Ich habe diesen Schlüsselanhänger bitronhome 902010/23

Leider bekomme ich beim anlernen folgende Meldung:

Error: Device 0x00124b0008e71661 "902010/23" not described in statesMapping.. undefined
New device joined '0x00124b0008e71661' model 902010/23
Interview successful: [object Object]

Könnte das mit rein genommen werden, den es ist meines wissens, der einzige Zigbee Schlüsselanhänger.

LG

**Comment by asgothian** [comment]
- is it listed as supported at zigbee2mqtt.io ?
- Which adapter version are you using ?

A.

**Comment by Schmusekater76** [comment]
Weitere Eigenschaften
Smarthome-fähig
ja
Schutzart
IP41
Vernetzung
drahtlos
Frequenzbereich
2400 MHz
Standards
ZigBee, BidCoS
SmartHome Systeme
Telekom Smart Home, Qivicon
Stromversorgung
Batteriebetrieb
Gehäusematerial
Kunststoff
Abmessungen (B x H x T)
38 x 65 x 15 mm
min. Betriebstemperatur
-10 ° C
max. Betriebstemperatur
50 ° C
Zulässige Luftfeuchtigkeit im Betrieb
85 %
Bedienungsart
Fernbedienung
Bemerkung
4 frei-belegbare Funktionstasten / optische Übertragungsbestätigung / mit Schlüsselanhänger


Which adapter version are you using ?

1.4.4

**Comment by Schmusekater76** [comment]
modelZigbee:902010/23
type:EndDevice
nwk:47845
manuf id:0
manufacturer:Bitron Home
power:Battery
app version:19
hard version:0
zcl version:1
date code:20150518
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
output clusters:genOnOff (6)
genLevelCtrl (8)

**Comment by asgothian** [comment]
Is this device listed as supported at zigbee2mqtt.io ? 

If not, then implementation in the zigbee-herdsman-converters is required up front, which is next to impossible to do without a device.

A.

**Comment by Schmusekater76** [comment]
Is this device listed as supported at zigbee2mqtt.io ? Das weiß ich nicht, gelistet ist es nicht, der Zigbee Adapter erkennt ihn aber, nur das man nichts schalten kann, es ist nur ein Fragezeichen.

**Comment by o0shojo0o** [comment]
https://www.zigbee2mqtt.io/information/supported_devices.html

**Comment by asgothian** [comment]
> Is this device listed as supported at zigbee2mqtt.io ? Das weiß ich nicht, gelistet ist es nicht, der Zigbee Adapter erkennt ihn aber, nur das man nichts schalten kann, es ist nur ein Fragezeichen.

Lets start at the beginning:

- Any device which adheres to specific zigbee guidelines can be paired with the zigbee Adapter. It will show up in the device list with a ? and will not generate any states and can only controlled via the developer tab.
- Any device which is "supported" by zigbee2mqtt.io (i.e. present in the List @o0shojo0o has linked) has the option to generate states as the support in zigbee2mqtt implies that a translation of "states" to "zigbee Messages" (the so called "converters" which give the Zigbee-Herdsman-Converters project its name) are present and can be used.
- Since approx. late December 2020, the Support in Zigbee2mqtt.io also includes "exposes", which is a method of telling the client (i.e. ioBroker.Zigbee) which states to generate to support a device. This means that a device which has full support in zigbee2mqtt.io should generate states in ioBroker.zigbee due to the exposes listed on the device.
- As an alternative to exposes, devices can be explicitly supported in ioBroker.Zigbee. This is achieved by defining the states the device is supposed to have and link them with the converters defined by the zigbee-herdsman-converters. At this point, a device will also gain the picture and some additional information.

As long as a device not listed as supported in the zigbee-herdsman-converters (which BitronHome902010/23 is not) there is little which can be done on ioBroker.zigbee to implement device support. For "standard" devices (lightbulbs, plugs, relays, dimmers, with the possible exception of any TuYa compatible device) it may be possible to implement device support in the zigbee-herdsman-converters with just some information about the device but without physical access to the device.

Again, in your case, this condition is not met, which means that Implementing support for the device requires for a developer to have access to the device.

A.
