### ISSUE TITLE
zigbee is not working, if iobroker is running from SSD

### ISSUE THREAD

**Issue by Cerunnos75** [ioBroker/ioBroker.zigbee#1071]
As decribed [here](ttps://github.com/ioBroker/ioBroker.zigbee/issues/1050) I has issues getting the adaptor to run. After several days of de/reinstalling ioboker, setting up the raspberry completely new, checkes different versions of node.js and npm, I figured out that the adaptor works neither with a Conbee II nor with a CC2531. 
After changing back to boot from SD-card, everything woked perfect again.
Seems the either USB-SSD creates conflicts with the serial port or some paths point wrongly.
If I can support with any log files, please let me know.

HW: Raspberry Pi 4 Model B Rev 1.4 with 8GB
SW: Raspbian GNU/Linux 10 (buster)
ioboker: Node.js    v12.22.1  NPM    6.14.12

**Comment by asgothian** [comment]
Please use a higher quality USB to SATA adapter. I would assume that the adapter is causing issues with the wireless for the zigbee connection. This is a known issue with running USB boot on a PI4, especially when using USB3

A.

**Comment by Cerunnos75** [comment]
Anny suggestions?
At the moment I use this one: [https://www.amazon.de/dp/B07D2BHVBD/ref=cm_sw_em_r_mt_dp_9TCA1X3CQ8A6PTDFY7E0?_encoding=UTF8&psc=1](url)
which is on the list of working adaptors: [https://jamesachambers.com/new-raspberry-pi-4-bootloader-usb-network-boot-guide/](url)

**Comment by asgothian** [comment]
I would try the following:
- change the cable against a different (longer?) cable
- run the SSD on USB2 rather than USB3
- See if you can place the SSD itself in a metal box to shield the controller from sending HF data

A decent article on the issue can be found here:
https://www.intel.com/content/www/us/en/products/docs/io/universal-serial-bus/usb3-frequency-interference-paper.html

Keep in mind that Zigbee is also using the 2.4 GHz Band.

A.

**Comment by Cerunnos75** [comment]
@asgothian thank you very much. So my first suspicion was kind of right that SSD (on usb 3) creates conflicts with the stick. 
I wanted to keed the SSD on USB3 to gain the speed advantage. Putting the stick away with a 2 meter extension cord did the job.
