### ISSUE TITLE
Discussion: Breaking change and Version 2.0

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#1137]
Hello all,

the ioBroker dev team introduced a new functionality for the ioBroker which, if implemented, will encourage adapters which deal with physical devices to correctly set roles and types for all states in order for their device detector to be able to identify the devices automatically.

This may need a breaking change for the Zigbee Adapter as not all devices currently follow this method, and for the most case, the Zigbee devices do not expose some of the "suggested" states as "battery Low" or "unreachable" in the way the device detector requires it.

Due to this, I would propose to set up a dev branch towards ioBroker.zigbee 2.0 with 3 goals in mind:
- Auto-configuration on new installs - only type and port should be needed to configure, the remaining configuration data should be possible to obtain from defaults or from the herdsman internal backup structure. Implementing this will require a change in the way the herdsman is initialised, paired with some critical changes in the Zigbee-herdsman to support this. The benefit for the ioBroker user would be that default new installations would automatically use "safe" network id, pan id and ext-pan id, and, on supporting coordinators allow for an autoselection of the Zigbee channel based on a network scan.
- Use of Herdsman Exposes for as Many devices as possible. The Plan here would be to flat out remove all non-essential states and devices definitions from the Zigbee adapter when generating the development branch and to rely on people with devices with issues to help us to get the most out of the exposes functionality, leaving explicit device configurations for devices which do not play well with the expose setup (again, the PTVO is a good example for this)
- Compliance with the new device definitions for all devices which are handled completely by exposes.

Thoughts on this ?

A.

**Comment by Apollon77** [comment]
Very important ... nothing will be "enforced" and also "battery low" and such are mostly optional fields ...

In fact it should better read: It would be beneficial if created devices and channels use the correct roles and types for relevant states ... :-))

**Comment by asgothian** [comment]
Thank you for the clarification. I updated the post above to reflect this. 

The way I see it, the benefits of setting correct roles and states for the device detector to use is so high that it does outweigh the changes of a breaking change in the zigbee Adapter - which was the reason for me to open this issue.

A.

**Comment by Apollon77** [comment]
I completely agree!! Especially for unexperienced used the benefits are outstanding! I just wanted to make it clear :-)
Mainly means: If a device can not offer a certain (optional) state then you do not need to struggle around and try to find something  ... just leave it out. the required ones are the importent ones

**Comment by kirovilya** [comment]
The ability to use the detector has appeared for a long time in iobroker.devices and iobroker.iot, so I'm surprised that something new awaits us :)
OK. We try to set the correct roles and types when creating states. Not for devices though. Or I'm wrong?
If somewhere the role and type is set incorrectly - let's set it correctly! I don't see a problem with this, it can be done in the current codebase.

You can refuse to use the descriptions of the devices specified in the adapter. But it is better to gradually, to make sure that we do not lose some functionality.

I do not see any critical changes in the proposed changes that seriously change the logic of the adapter, so I suggest not to overstate the version to 2.0, as users will look for something new for themselves, but will not find :)

**Comment by asgothian** [comment]
One of the ideas was to go away from explicit device definitions with this, so that we don’t have to deal with editing each and every device. That would swap a lot of states, hence the 2.0 suggestion.

I don’t mind not to use that Version number, but I really would love to drop most devices from devices.JS and clear out the states.JS as well

a.

**Comment by kirovilya** [comment]
You can delete it gradually, making sure that the new states of the device to be deleted remain functional. Or it can be tough - deleting everything and then adding the necessary :)

What we are discussing now is our internal problems :) Better, let's think about some innovations that users will really need. Any ideas?
* I see the need for a correct backup-restore procedure so that you can unload and transfer it to another computer or another stick.
* It is also necessary to revise the "binding" and add "reporting".
* I would also add the ability to change the picture (along with renaming the device so that you can insert your picture)
* In the dashboard the ability to sort and filter by the date of addition, by the signal level, by the battery level.

One more innovation, I would attribute as a whole to the iobroker - event handlers. Now, to see what function is executed when the button is pressed, you need to go to the scripts and look for the code there. It would be nice to see the handler code like "history" in admin states list - right next to the state on which it is used. And so that a new handler can be added right next to it.

**Comment by Apollon77** [comment]
@kirovilya 
> The ability to use the detector has appeared for a long time in iobroker.devices and iobroker.iot, so I'm surprised that something new awaits us :)

In fact yes it is there for some time and we clearly see that the use is kind of limited because of the described facts that many adapters are ot structuring the sttes as needed ... And thwts why the topic was discussed in the last developer meeting with the call to the devs to check their adapters.

That change also might require to split devices meaningful into channels or such - but this is a big "it depends". So yes ideally it is "just" a fix in "role" and "datatype" (if relevant). SO if it really becomes breaking depends on where the mismatches are.

To yourt last innovation idea: The current structure with each adapter allowing to have own event handlers on state-ids and such this will not really work that well. For customer logic it is mainly the JavaScript Adapter relevant, bt also here you can use regex and other stuff to subscribe a script to many object-ids or also a subscribe can be "once" ... and I do not start with Aliasses and subscribes to them which in the end is also on the read object... so this is tooo complex and also the information is too spreaded into all adapter processes that I do not see a good way to achieve this.

**Comment by Apollon77** [comment]
Ps: also an Option could be to leave existing States Andrade new compatible. Could especially work for unreach and lowbat maybe. Would then also not breaking

**Comment by asgothian** [comment]
> Ps: also an Option could be to leave existing States Andrade new compatible. Could especially work for unreach and lowbat maybe. Would then also not breaking

I am aware of this. Unfortunately, there are a number of strange implementations for specific devices which are not mirrored to others of a similar type, and the zigbee Adapter already has a large number of states which are of questionable use in the long run.

I would rather go ahead and make one breaking change and then stick with the correct definitions than inflate the adapter with duplicates.

A.

**Comment by asgothian** [comment]
> You can delete it gradually, making sure that the new states of the device to be deleted remain functional. Or it can be tough - deleting everything and then adding the necessary :)
> 
> What we are discussing now is our internal problems :) Better, let's think about some innovations that users will really need. Any ideas?
> 
> * I see the need for a correct backup-restore procedure so that you can unload and transfer it to another computer or another stick.

Another computer should not be much of an issue. Another stick is a different matter, as the save files from the herdsman do not seem compatible at the time. It might in future work for another stick of the same kind, but it will require adapter action as long as the coordinator itself is part of the data. Additionally, both bindings and reportings would need to be rebuilt as they are stored on the devices as far as i know.

> * It is also necessary to revise the "binding" and add "reporting".

Yes, this is something which could use a rework.

> * I would also add the ability to change the picture (along with renaming the device so that you can insert your picture)

I am very hesitant on this for a number of reasons:
- the adapter will need to store the changes somewhere other than the states db, as it will need to rebuild the states when an instance is removed and added again
- we would need to use adapter storage for the images
- having device specific images is quite a bit of work for something few people actually see and will lead to requests like exposing the dashboard to a vis or exposing the map to a vis (that we already had)
> * In the dashboard the ability to sort and filter by the date of addition, by the signal level, by the battery level, by type of device.
This sounds interesting. I would want to add 2 things to that: 
- Display the room on the dash card
- Offer an option to make the device card the default card rather than the dash card. 

Alongside this we would need a fix for device cards without content on OS X devices (i have seen this for safari, firefox under certain conditions, chrome on certain conditions) but lack the skillset to fix it.

A.

**Comment by kirovilya** [comment]
@Apollon77 
> For customer logic it is mainly the JavaScript Adapter relevant, bt also here you can use regex and other stuff to subscribe a script to many object-ids or also a subscribe can be "once" ... and I do not start with Aliasses and subscribes to them which in the end is also on the read object... so this is tooo complex and also the information is too spreaded into all adapter processes that I do not see a good way to achieve this.

I meant the idea of quickly developing event handlers. I'm talking about simple handlers: I pressed a button and turned on the lamp.
In most cases, an event handler is hung on one state, and not in bulk - such handlers can be grouped in a javascript adapter, for example, in a separate folder.
In such handlers, one source - one state, so it would be convenient to be able to create a handler from the status bar.
Or, make a button near the state that will show all scripts where this state is used :)

@asgothian 
> I actually consider these internal problems important 

yes, there are internal problems, they must first be identified and then corrected.

for example, I do not yet understand what needs to be finalized with roles and types ... because I do not understand the problem ... examples are needed.

As for the descriptions of the devices in the adapter, let's cut out all the bulbs first, then the switches, then the sockets, then the sensors, etc.
But I would leave the possibility to leave the device description in the adapter in order to be able to handle complex cases when it is difficult to automatically convert the exposes to states.

> Alongside this we would need a fix for device cards without content on OS X devices

I'll take it upon myself

**Comment by kirovilya** [comment]
> Of course there should be a chance for complex device definitions. I intend to actually add an "external" device definition option for people who want to test things and try, so that the adapter code does not need to be modified for the test.

is it similar to external converters? now there is already such functionality in the adapter.
