### ISSUE TITLE
Curtain Switch

### ISSUE THREAD

**Issue by MasterTH-PyPy** [ioBroker/ioBroker.zigbee#1159]
Hi,

i just added a zigbee curtain switch to my iobroker installation, but i cannot manage it quiet well.
It get imported as TS130F, but i think this is not the correct type of device.

Currently i asked the seller to send me the datapoints, maybe i can get them. Otherwise, can you explain me how to retrieve them from the device itself?

this is the switch: https://de.aliexpress.com/item/1005002440096509.html?spm=a2g0o.cart.0.0.16513c00pKL48m&mp=1

thank you for your help

**Comment by Pedder007** [comment]
Hi there, I have got a couple of them already installed. [They look a bit other](https://de.aliexpress.com/item/4000311591651.html?spm=a2g0s.9042311.0.0.7f744c4dboEyz1), but I guess they are all the same (=TS130F).

Depending on the used adapter, the data points look a bit different, but similiar:
ZigBee
![image](https://user-images.githubusercontent.com/44653371/133502597-090188ae-fa60-427f-bf84-b024c369e0de.png)

deCONZ:
![image](https://user-images.githubusercontent.com/44653371/133502683-bc349e71-e4a3-42b1-848b-b13c1ec1710e.png)

As I would like to perspectively migrate from deCONZ to ZigBee, it would be good, if the data point 'moving' of the ZigBee adapter would work propperly. Currently nothing happens when changing the DP. The shutter can only be steered via the 'postion' DP, but with this, cannot be stopped somewhere (e. g. by steering via a WEB GUI button).

As deCONZ is reachable via API I'm currently using a work around for stopping the shutter via a shell command:
````curl -X PUT http://127.0.0.1:80/api/[deCONZ Key]/lights/38/state -d '{"stop":true}' -s````
This produces a warning in ioBroker
![image](https://user-images.githubusercontent.com/44653371/133503509-797baf3d-d0fa-4933-b957-d07627e13366.png)
but works.

Thus I would be happy to see a propper usability of the 'moving' data point.

If this could help, one of the Pimatic developers (where I freshly migrated from) already did the job in a great way. I might ask him to re-use his sourcecode here in ioBroker?

**Comment by asgothian** [comment]
We are talking about TuYa devices. tuYa provides hardware and a software kit to developers to adapt to their needs. Which is why devices which look Similar act differently. Devices which report the same Id act differently. Just search the list of supported devices on zigbee2mqtt.io for Ts0601 for some fun.

it is likely that your version does not fully match the version implemented in the zigbee-herdsman-converters. As TuYa loves to use nonstandard clusters and messages, this is not easily fixed.

A.

**Comment by Pedder007** [comment]
@asgothian thanks for your quick reply!
In know this about Tuya already, having seen a couple of similar discussions here on Git and elsewhere also regarding other devices😉. Sometime also already the learning process to the coordinator works other…
But to maybe support on a solution here from my side: As I‘m using deCONZ and thus can access the devices also via the deCONZ gui (much more detailed than the Phoscon App), I would be able to deliver the respective needed clusters and related data fields. The deCONZ gui shows this all in detail. Thus we would not need to wait for an answer from the seller, as @MasterTH-PyPy outlined above.

**Comment by asgothian** [comment]
We can have a look at it this weekend via (iobroker) Discord / Anydesk, if you are free.

A.

**Comment by Pedder007** [comment]
Hi, I have to check. If it works, then it would be Sunday early evening.
And I would have first to register at Discord / Anydesk, as currently only one of my kids is using it… 😉 
I come back again here later ….

**Comment by asgothian** [comment]
AnyDesk is without registration and optional. Sunday would need to be between 6 and 8, as I am busy after 8. I can toss a discord invite link to the iobroker discord, or you take it from the forum.

A

**Comment by Pedder007** [comment]
Hi  again, btw. 6 and 8 would be fine.
I just tried to join discord via the respective links in the form (e.g. https://discord.com/invite/HwUCwsH), but when klicking the ‚accept invitation‘ button, it says ‚Safari isn‘t able to open as the address seems not to exist‘. I additionally disabled my PiHole, but that wasn‘t the reason.
Thus maybe better send a dedicated discord link.
I might be online also today in the evening but my plan was to setup my Unifi-GW newly, incl. ioBroker Slave …
