### ISSUE TITLE
Add an object to start pairing mode 

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#1164]
I would like to be able to start the pairing mode from Vis. It would be great to have a button object to do this.

**Comment by Ilovegym66** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/991

**Comment by asgothian** [comment]
I do not see this as feasible due to the attached risks and options for misuse.

It is not hard to add such a state, but adding this will open the system up to a large number of operator related issues which will be hard to debug and fix.
- opening the network when the adapter is not in the correct state
- Script based network opening resulting in network which is open 90+ % of the time

note that certain actions may be delayed / changed when the network is open due to differences In the zigbee behaviour.


A.
