### ISSUE TITLE
Aqara Light Bulbs decreases brightness automatically

### ISSUE THREAD

**Issue by Shadesh** [ioBroker/ioBroker.zigbee#1211]
Recently I got a very strange problem with some of my Arara light bulbs (ZNLDP12LM). After updating the firmware of them (with iobroker build in updater) the brightness decreases automatically to random values and I have no idea why. I already stopped all scripts to be sure its no a typo in one of them. I can set it to 100 but randomly it gets changed to a lower value. Current firmware build seems to be.

date code:09-01-2020
build:1.32

Is there any way to find out what process / script or whatever changes the brightness? Or is there a know process / error why this bulbs are decreasing his brightness automatically?

**Comment by asgothian** [comment]
The only way to do that is to set a trigger to the brightness value and log the `obj.state.from` entry. (see [here](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state))
If the source is the zigbee adapter then it is very likely that the change is triggered by the lightbulb itself. This can be caused by a hidden binding to a remote or a hidden group affecting its brightness. Both should be removable by resetting the bulb and pairing it again.

A.
