### ISSUE TITLE
adapter does not change name in whole object tree

### ISSUE THREAD

**Issue by andre1974** [ioBroker/ioBroker.zigbee#1242]
Hi there,

if i change the name of a device in the Zigbe adapter, only the name behind the folder symbol is changed in the objects.
Earlier it used to be that the name was then changed in the entire object tree of the device.

Can anyone help me to make it work again?

Using 1.6.4 from GitHub
![19-10-_2021_23-53-56](https://user-images.githubusercontent.com/11474126/138052679-0f8d7ec5-e018-4a79-aa64-6bc12b26d051.jpg)

**Comment by andre1974** [comment]
Still not fixed

**Comment by Blechbixn** [comment]
Yeah, same Problem here.
Its difficult to set up overviewing Blockly's with just the state "is open" for example.
Would appreciate a fix.
![grafik](https://user-images.githubusercontent.com/88854316/194398252-74702e25-498f-4cf8-a452-cdd072fdfa79.png)

**Comment by Apollon77** [comment]
Hm ...But it is clear that states under the ID "folder" all belong to this?! If we start doung this here then in fact nearly ALL other adapters needs to be adjusted too ... SO maybe itis easier to try to adjust something in blockly to maybe better show the state path?

**Comment by andre1974** [comment]
It used to work in earlier Versions. 
So why not just put it back?
It is really annoying the way it is.

**Comment by asgothian** [comment]
Why not put it back ? Simply speaking:

It is a lot of work, and as far as i can see there are two people who want this change. The state names are generated automatically for the most part nowadays - adding  a placeholder for the device name and renaming all states whenever the device name is changed is not as trivial as it seems.

I am with Apollon77 here. If this is a big enough issue, then i would suggest to open a change request at the Blockly Adapter to include not just the state name in the display but also the device containing the state name.

This would fix the problem where it occurs, rather than provide a workaround for just one adapter.

A.
