### ISSUE TITLE
Device 0x000d6f0013e9ca78 "511.020" not described in statesMapping.

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.zigbee#1248]
iluminize Zigbee 3.0 LED-Controller 4x 5A, 12V-36V, für duo-weiße (CCT) LEDs, Lightlink & Touchlink (4x 5A duo-weiß) 
Weitere Informationen: https://www.amazon.de/dp/B07LBTRNT7/ref=cm_sw_em_r_mt_dp_3EKS91WWFVYC08EE0PDN?_encoding=UTF8&psc=1

![image](https://user-images.githubusercontent.com/14368811/139537260-f0efc098-f184-444b-87a5-1b2e6b6c01c1.png)

**Comment by asgothian** [comment]
which version did you tests this with ?

**Comment by Zefau** [comment]
zigbee: v1.6.3
js-controller: 3.3.18
Node.js: v14.18.0 / npm 8.1.0

**Comment by Zefau** [comment]
Brauchst du noch Informationen? Kann das behoben werden? Ich sehe, dass die Problematik sogar ein eigenes Label hat? :-)

**Comment by asgothian** [comment]
The kind of issue has its own label because for 95% of the devices (yours included) the issue cannot be fixed in the zigbee adapter. It is relying on information provided by the zigbee-herdsman-converters to integrate standard devices.

I put together a cheat sheet how to deal with this issue as well as a document which describes how to obtain the necessary information to try and implement the device in the zigbee-herdsman-converters.

In order to implement the device, hardware access to the device is usually needed.

A.

**Comment by asgothian** [comment]
Please update to 1.6.11 to verify if the device is supported. If it is not, reopen this issue
