### ISSUE TITLE
Aqara Temp Sensor

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.zigbee#1335]
Kann man die pressure calibration auch im Adapter (z.B. hinten bei tab Entwickler) ausführen ?
vgl. thread:
https://forum.iobroker.net/topic/51361/zigbee-wie-oft-erfolgt-aktualisierung/46?_=1642356017640

**Comment by asgothian** [comment]
This is not currently possible as the calibration data is held in zigbee2mqtt, rather than the zigbee-herdsman-converters.

The zigbee Adapter would need to hold an offset value in its own data to do that. It may be possible to implement that for one device and one state, but I do not consider this sensible.

a more general variant with calibration options for more states makes more sense but also more effort.

A.
