### ISSUE TITLE
Device '0xXXXXXXXXXXX' announced itself

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1364]
In my protokolls I find these messages:

![image](https://user-images.githubusercontent.com/5464553/153043203-12759ea6-7510-4f8a-834d-acf106739faf.png)
Is this a bug in Version 1.6.14 ?

Rgds
UweLoyal

**Comment by Shadesh** [comment]
This is not a bug, from time to time devices announces it self to the zigbee adapter. It could be a problem if this happens more then e.g. once a week for the same devices. If so, try to pair the devices again, you don't have to delete the device before. Otherwise, ignore it if both of the devices are works as desired.
