### ISSUE TITLE
No Battery Percent in Objects IOBroker after updating to 1.6.15 for Xiaomi WSDCGQ11LM

### ISSUE THREAD

**Issue by VienetVienet** [ioBroker/ioBroker.zigbee#1370]
Battery Percent was working perfect before update.

**Comment by ninja-warrior** [comment]
Same here.

**Comment by asgothian** [comment]
Please verify if the WSDCQ11LM publishes battery percent. In order to do that:

- enter the Address of the device(s) (separated by a ; if multiple) into the state `zigbee.0.info.debugmessages` 
- check the log for warning messages with the keyword 'ELEVATED' and relating to the battery percentage.
- Observe this for at least 36 hrs.

The device Address is the 16 digit hex number used as device ID (e.g. zigbee.0.00abcd00f9346241 => Address is 00abcd00f9346241)

A.

**Comment by VienetVienet** [comment]
Done and waiting...I hope that's right there ... 

![grafik](https://user-images.githubusercontent.com/99735757/154245766-4420f4ac-9ede-4ac3-aa50-aa8f1ca3cfce.png)

**Comment by VienetVienet** [comment]
Got this now ...
![grafik](https://user-images.githubusercontent.com/99735757/154249202-20e0c629-8528-48ec-8d98-cb4ab6fcf94d.png)

**Comment by asgothian** [comment]
Please post Logs as text in the future - a lot more readable than screenshots.

The message clearly states that the device sends a low voltage (2.845 v) which translates into a dead battery (0%).

Please see [here](https://github.com/Koenkk/zigbee2mqtt/issues/8499) for the changes in the zigbee-herdsman-converters.

A.

**Comment by VienetVienet** [comment]
Ok, it was 16% before - I'll change the battery later and check again.

**Comment by VienetVienet** [comment]
After battery change:

2022-02-16 14:30:09.933	warn	ELEVATED publishToState: value generated '100' from device 00158d0007df608e for 'Battery percent'
zigbee.0
	2022-02-16 14:30:09.933	warn	ELEVATED publishToState: value generated '3.245' from device 00158d0007df608e for 'Battery voltage'
zigbee.0
	2022-02-16 14:30:09.933	warn	ELEVATED publishToState: message received '{"voltage":3245,"battery":100}' from device 00158d0007df608e type 'WSDCGQ11

Sorry :-)

**Comment by asgothian** [comment]
Closing this - behavior is as desired.
