### ISSUE TITLE
Problem with Group and Color Temp

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1390]
Changing Color Temp generates a Warning:
unread colortemp change for group members ["0xXXXXXX1","0xXXXXXX2","0xXXXXXX3","0xXXXXXX4","0xXXXXXX5"]
The Lanps in Group are Lidl HG06106A

I think the numberrage of Color Temp is not identical.
Group 200-9000
Lamp 150-500

**Comment by asgothian** [comment]
This warning is generated as the lidl lamps do not allow for the color temp to be read, so the group cannot upgrade the ct value for the lamp itself.

the number-range is immaterial.

A.

**Comment by UweLoyal** [comment]
Color Temp is Readable!
I do it also with my scripts!


{
  "type": "state",
  "common": {
    "name": "Color temperature",
    "type": "number",
    "read": true,
    "write": true,
    "role": "level.color.temperature"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1644311892117,
  "_id": "zigbee.0.588e81fffef66572.colortemp",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by asgothian** [comment]
You are reading the iobroker state. The adapter is requesting to read the color temp from the device but the device does not respond.

A.

**Comment by UweLoyal** [comment]
Is it possible to fix that Problem?

**Comment by asgothian** [comment]
This is not something the adapter can change. A bit of background:

- The state changes are sent to the "group", not to the individual device by the zigbee adapter. 
- The group is defined on the coordinator, and the changes are then sent to the members. The system relies on the group members to inform the coordinator about value changes.
- Since most devices do not report changes made through the group system, the zigbee adapter generates a "value query" as defined by the zigbee-herdsman-converters. It is this subsystem which generates the warning messages.
- You can test this subsystem yourself by activating the "device query" state. The logic which data to query is taken from the zigbee converter definitions. Only states which advertise that they can be read are actually attempted. If you check the log you will see that the converters advertise readability for several objects which actually cannot be read. Most notable offenders are color_temp and color.

For the adapter, there are 2 options:
- Discard the attempt to query states, and with it, give up on keeping the lamps own states updated to the actual values on the lamp if set by the group
- Retain the read attempt and accept the warning message.

On a side note - the slider should still work and change the colortemp of the bulbs. It does for all my groups which support color. If it does not, this is not linked to the warning message but an internal error of the lidl bulb which warrants further testing. As i do not have said lamps i will not be able to perform those tests myself.

A.

**Comment by UweLoyal** [comment]
Is it possibel, that a Hosts update generate that problen, today I had the 2nd Udate.
New error are now generated
![image](https://user-images.githubusercontent.com/5464553/156929741-45717fdf-3e67-4fd9-95e3-0efdb4a1d525.png)

and

![image](https://user-images.githubusercontent.com/5464553/156929824-8cbec258-c69c-4d29-be12-bb40f64684de.png)

after runnig this script

const Licht_Decke_extern_node_root  = "zigbee.0.group_1";
const dot = '.';
setState(Licht_Decke_extern_node_root + dot + 'colortemp',200);
log(getState(Licht_Decke_extern_node_root + dot + 'colortemp').val);
setState(Licht_Decke_extern_node_root + dot + 'colortemp',300);
log(getState(Licht_Decke_extern_node_root + dot + 'colortemp').val);

witch generte a flash of on/off of all Lamps in Groupe.
Bevore the last update this was not generated by the script.

You reopend the report, you done this because found somethig?


Rgds
UweLoyal

**Comment by asgothian** [comment]
No. I reopened the report so you would not create additional issues.

The original assessment stays. The adapter is working as extended.

The first log you posted (btw - logs should **never** be posted as screenshots) have nothing to do with this issue. This is an issue which hints at a problem with your zigbee network as you are flooding the zigbee buffer with requests which cannot be handled in a timely manner.


The getState commands do not read the value from the hardware, but only from the iobroker state database.

The script itself seems normal, but this can be a mistake as it is only a script stub. As a rule of thumb, it should be avoided to set the same zigbee state to different values without at least 20 to 50 ms delay between the operations.


Lastly, there is no 4.0.18 version of the zigbee Adapter.

A.

**Comment by UweLoyal** [comment]
4.0.18 Actual Version of Hosts

**Comment by asgothian** [comment]
The host version has nothing to do with any of the errors posted.

- The warnings are generated by the zigbee adapter as explained above.
- The error messages are generated by the zigbee-herdsman due to the message buffer on the zigbee coordinator to be full. This is an indication of either wireless issues or too many commands sent in too short a time.

A.

**Comment by UweLoyal** [comment]
I's realy funny, asgothian (https://github.com/ioBroker/ioBroker.zigbee/issues/1390) say ask the hardware producer, slaesh (https://slae.sh/projects/cc2652/#). slaesh say, ask Koenkk (https://github.com/Koenkk/zigbee2mqtt/issues/11875) and Koenkk, sais ask asgothian.

Who can now help me after staying again at the beginning?

In hope for Help!

Rgds
Uwe Loyal

**Comment by asgothian** [comment]
You may want to read what i wrote above. You have been sending commands to the zigbee network (to the same device) in a flood with (only in your log section) 6 messages in 200 ms. I don't know how much you send before that, but that is entirely too many.

A.

**Comment by UweLoyal** [comment]
I whant to ask you in another way:
Who has to fix the Bug, that the Groupslider of color temperature will not generates this error?
Everybody say, thats not my problem, but thats not the way to fix that bug!
So please coordinate this with all known developer and help me and all other user to get a with no errors working system.

![image](https://user-images.githubusercontent.com/5464553/158842822-216360ff-2408-4b6e-a0b6-471115af9543.png)

![image](https://user-images.githubusercontent.com/5464553/158842055-0b6580c8-a3a6-4493-b12f-f42b04f374cf.png)

The same slider of Lamp works fine with no errors!

![image](https://user-images.githubusercontent.com/5464553/158842441-82db000f-8b54-4a2f-b21b-169d16e01c2e.png)

Rgds
Uwe Loyal

**Comment by asgothian** [comment]
The answer to that question depends on a number of things.

Option 1:
There is a fix within iobroker, one which i can do with a simple edit. Doing that would mean that a change of any value in the group will not ever update the value on the group members themselves unless the group members report the changed value. 

This is an easy fix, but it removes requested functionality, which is why i do not intend to follow this route.

Option 2: Figure out why the lamp does not respond as expected when queried for the color temperature. This can have one of two reasons:
1. There is a bug in the zigbee-herdsman-converters implementation of the colortemp state in a way that the read request is handled.
2. The lamp itself may simply not respond to a request to read the colortemp - in this case, the documentation on zigbee2mqtt.io is not correct. This can only be fixed on the lamp by a firmware update.

Option 3: Rewrite the entire group function to not rely on zigbee network group objects but zigbee adapter group objects instead where the separate entities are switched by the adapter rather than issuing a single group command. This is
- a lot of work
- stupid, as it increases the load on the configurator significantly and bypasses a core zigbee function.

The only viable option in my eyes is option 2. I have made an attempt at it several times, but never made any real headway. The code used to read the colortemp is identical to the code used to read the on/off state and brightness value - it works flawlessly in both cases.

A.

**Comment by UweLoyal** [comment]
Anouther thing is also not logical for me:
Changing Color temperature directly on your Zigbee adapter slider for th Lamp generates no errror.
Using Groupe Color temperature slider generates an error.
Do you can explain me this effect, for me its is not logical, because all ends in the same Lamp. Logical for me is would be: both generates an error or both genaerates no error.

I would be happy, if you could explain it for me.

Rgds 
Uwe Loyal

**Comment by asgothian** [comment]
I already explained it above:

When you talk with the lamp directly, the value is written into the color_temp state for the lamp and then sent to the lamp. The lamp confirms that it has received it so we can confirm the value.

When you talk with the group the value is sent to the group, which internally sends it to all members, bypassing the lamps own iobroker states. The group does not confirm the success of the change, so we cannot confirm the state change. We cannot update the lamps color_temp values unless the lamps report it, which they mostly don't. This is why we attempt to query it - without an answer.

A.

**Comment by asgothian** [comment]
A Test branch exists at 
https://github.com/asgothian/ioBroker.zigbee/tarball/H459

Please note that this branch may have additional changes which may or may not cause additional effects.

A.
