### ISSUE TITLE
IKEA Tradvi Shortcut Button - Error Message at ioBroker Log / State naming suggestion

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.zigbee#1399]
I've tried to connect my first IKEA TRADVI SHORTCUT Button. During pairing an error was raised although the pairing has worked.
Please see ioBroker Log output below. (This is a screenshot of the log so the newest logs are at top !)

In addition the Zigbee Adapter lists the following 4 states

- on
- off
- brightness_move_up
- brightness_stop

These names are not really intuitive. "on" is activated when the button is pressed short. "off" could not be triggered be me at all. "brightness_move_up" is activated when the button is pressed long and "brightness_stop" is activated after releasing a long press.

In my opinion the device can signal only short an long press. So at least the brightness states should be renamed to i.e. long_press.
And the off state should either be removed if it cannot be activated at all.

ioBroker log concerning the error message following:

```
zigbee.0 | 2022-03-27 20:57:07.402 | info | Zigbee: stop joining
zigbee.0 | 2022-03-27 20:54:30.531 | info | DeviceConfigure successful 0x2c1165fffeccfb66 TRADFRI SHORTCUT Button
zigbee.0 | 2022-03-27 20:54:23.315 | info | Configuring 0x2c1165fffeccfb66 TRADFRI SHORTCUT Button
zigbee.0 | 2022-03-27 20:54:23.311 | info | Device '0x2c1165fffeccfb66' is supported, identified as: IKEA TRADFRI shortcut button (E1812)
zigbee.0 | 2022-03-27 20:54:23.310 | info | Successfully interviewed '0x2c1165fffeccfb66', device has succesfully been paired
zigbee.0 | 2022-03-27 20:53:53.308 | error | Device 0x2c1165fffeccfb66 "undefined" not described in statesMapping.
zigbee.0 | 2022-03-27 20:53:40.898 | warn | Device '0x2c1165fffeccfb66' announced itself
zigbee.0 | 2022-03-27 20:53:38.660 | info | Starting interview of '0x2c1165fffeccfb66'
zigbee.0 | 2022-03-27 20:52:55.994 | info | Zigbee: allowing new devices to join.

**Comment by asgothian** [comment]
The naming of the states should be generated by the messages the device sends. This should be done automatically without any logic to rename the states within the iobroker in order to be able to support devices without any device specific code within the adapter itself.

Currently, there is a large number of devices with adapter owned code for their integration. Any of those devices run the risk to stop working on an update of the zigbee-herdsman-converters.

With regards to the device in question:
- either it is currently using a adapter specific configuration. If that is the case, it is matching the device messages for names, and a change away from that is not sensible.

-alternatively, it is already using the exposes to generate the state names, in which case adding adapter specific code for this device is going agains the direction the adapter is going.

A.

**Comment by mcm1957** [comment]
Thanks for your explanation. I cann fully accept the arguments. The messages have indeed such misleading names - biut thats not the fault of the adapter.

Why theres a "off" state which is always null (at least until now) cannot be really explaned this way but it does not really hurt. 

Thanks for reading / commenting my message
And thanks for the effort to keep this adapter working.
