### ISSUE TITLE
Moes MS-108ZR Attribut „invert_cover" not available

### ISSUE THREAD

**Issue by Xerxes55** [ioBroker/ioBroker.zigbee#1515]
invert_cover: Inverts the cover position, false: open=100,close=0, true: open=0,close=100 (default false). The value must be true or false
[#](https://www.zigbee2mqtt.io/devices/MS-108ZR.html#exposes)
This object is not available in Zigbee adapter.

**Comment by asgothian** [comment]
The invert_cover is provided as device specific configuration within zigbee2mqtt.io. It is not passed to the hardware but instead modifies the converter at runtime. 
No respective functionality Is present in the zigbee adapter. Since there is no dedicated device implementation for said device, this will most likely remain as the option is not included in the zigbee_herdsman_converters exposes.
