### ISSUE TITLE
nous_lcd_temperature_humidity_sensor: NOT RECOGNIZED DP

### ISSUE THREAD

**Issue by fzoellne** [ioBroker/ioBroker.zigbee#1556]
Hi,

I have a SZ-T04 device that is recognized and working so far ok.
However, in the log there is this message shown:

`zigbee-herdsman-converters:nous_lcd_temperature_humidity_sensor: NOT RECOGNIZED DP #20 with data {"dp":20,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,6]}}
`
`zigbee-herdsman-converters:nous_lcd_temperature_humidity_sensor: NOT RECOGNIZED DP #18 with data {"dp":18,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,120]}}
`
What does it mean ?

**Comment by asgothian** [comment]
This is an indication that the device you have (a TuYa Device) is accessed with an assumed device configuration in the zigbee-herdsman-converters library but not actually the same device, as it sends data which the converter does not expect.

May be fixed in newer versions of the library
Must be closed in the zigbee-herdsman-converters project.
