### ISSUE TITLE
Cannot read properties of undefined (reading 'Error')

### ISSUE THREAD

**Issue by dereme12** [ioBroker/ioBroker.zigbee#1778]
Hi, my iobroker used to run smoothly with my cc2531. After the system crashed and I had to reinstall everything, the zigbee adapter refuses to communicate with the stick. I also ordered a new sonoff zbdongle-e but still get the same results. Does anybody have an idea where this is coming from?

`

host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.612 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.611 | error | Caught by controller[1]: at Zigbee.doConnect (/opt/iobroker/node_modules/iobroker.zigbee/main.js:345:18)
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.611 | error | Caught by controller[1]: at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.611 | error | Caught by controller[1]: at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.610 | error | Caught by controller[1]: at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.610 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.610 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'Error')
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:30.609 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-07-04 18:06:30.025 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-07-04 18:06:30.024 | info | terminating
zigbee.0 | 2023-07-04 18:06:30.024 | warn | Failed to stop zigbee during startup
zigbee.0 | 2023-07-04 18:06:30.018 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-07-04 18:06:30.016 | info | cleaned everything up...
zigbee.0 | 2023-07-04 18:06:30.011 | error | Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-07-04 18:06:30.011 | error | TypeError: Cannot read properties of undefined (reading 'Error') at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56 at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1) at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1) at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32) at Zigbee.doConnect (/opt/iobroker/node_modules/iobroker.zigbee/main.js:345:18)
zigbee.0 | 2023-07-04 18:06:29.986 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-07-04 18:06:29.986 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-07-04 18:06:29.985 | error | Error herdsman start
zigbee.0 | 2023-07-04 18:06:29.985 | error | Failed to start Zigbee
zigbee.0 | 2023-07-04 18:06:29.984 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
zigbee.0 | 2023-07-04 18:06:09.800 | info | Installed Version: iobroker.zigbee@1.8.10
zigbee.0 | 2023-07-04 18:06:09.405 | info | Starting Zigbee npm ...
zigbee.0 | 2023-07-04 18:06:09.403 | info | delete old Backup files. keep only last 10
zigbee.0 | 2023-07-04 18:06:09.314 | info | starting. Version 1.8.10 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.16.1, js-controller: 4.0.24
host.FUTRO-S740-2c54050c | 2023-07-04 18:06:06.865 | info | instance system.adapter.zigbee.0 started with pid 3225
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | Caught by controller[1]: at Zigbee.doConnect (/opt/iobroker/node_modules/iobroker.zigbee/main.js:345:18)
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | Caught by controller[1]: at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | Caught by controller[1]: at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | Caught by controller[1]: at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.840 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.839 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'Error')
host.FUTRO-S740-2c54050c | 2023-07-04 18:05:36.839 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-07-04 18:05:36.262 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-07-04 18:05:36.262 | info | terminating
zigbee.0 | 2023-07-04 18:05:36.261 | warn | Failed to stop zigbee during startup
zigbee.0 | 2023-07-04 18:05:36.255 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-07-04 18:05:36.253 | info | cleaned everything up...
zigbee.0 | 2023-07-04 18:05:36.249 | error | Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-07-04 18:05:36.248 | error | TypeError: Cannot read properties of undefined (reading 'Error') at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56 at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1) at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1) at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32) at Zigbee.doConnect (/opt/iobroker/node_modules/iobroker.zigbee/main.js:345:18)
zigbee.0 | 2023-07-04 18:05:36.224 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'Error')

`

**Comment by dereme12** [comment]
ls -la /dev/serial/by-id

gives me

insgesamt 0
drwxr-xr-x 2 root root 60 Jul  4 18:11 .
drwxr-xr-x 4 root root 80 Jul  4 18:11 ..
lrwxrwxrwx 1 root root 13 Jul  4 18:11 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD398E-if00 -> ../../ttyACM0

**Comment by arteck** [comment]
also with GIT version ?

**Comment by dereme12** [comment]
The installation from GIT does not seem to work. The installation log does not show any errors but the adapter does not appear in the instances menu.

I activated the expert mode, used the cat symbol and chose zigbee from the dropdown.

**Comment by dereme12** [comment]
Today I have set up my raspberry with iobroker. I am getting the same results though. 
So it does not seem like the pc or os are the issue.

**Comment by dereme12** [comment]
GIT version did not change anything (1.8.13)

**Comment by mostschaedel** [comment]
`2023-07-10 22:00:32.016  - error: zigbee.0 (79390) Send command to 0x14b457fffe7346e9 failed with no error code (Timeout - 51888 - 1 - 7 - 768 - 11 after 10000ms)
2023-07-10 22:00:32.017  - error: zigbee.0 (79390) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-10 22:00:32.017  - error: zigbee.0 (79390) unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
2023-07-10 22:00:32.024  - error: zigbee.0 (79390) TypeError: Cannot read properties of undefined (reading 'Error')
    at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
    at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
    at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
    at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
    at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)
    at /opt/iobroker/node_modules/iobroker.zigbee/main.js:707:26
2023-07-10 22:00:32.024  - error: zigbee.0 (79390) Cannot read properties of undefined (reading 'Error')
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'Error')
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)
2023-07-10 22:00:33.098  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:707:26
2023-07-10 22:00:33.098  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

I can confirm this behaviour. Happens since friday (updated debian to bookworm and node to 18)
Tried the release-version as well as from github.

**Comment by arteck** [comment]
switch off sentry..and check again .. with new GIT version

**Comment by mostschaedel** [comment]
seems to work properly now.
the timeout error is still logged but the adapter doesn't crash anymore :-)

**Comment by dereme12** [comment]
Still not working for me but the log changed a bit:
`

zigbee.0 | 2023-07-11 20:02:56.535 | error | getGroups: caught error: TypeError: Cannot read properties of undefined (reading 'getGroups')
-- | -- | -- | --
zigbee.0 | 2023-07-11 19:45:39.196 | error | getGroups: caught error: TypeError: Cannot read properties of undefined (reading 'getGroups')
zigbee.0 | 2023-07-11 19:41:59.851 | error | Error herdsman start
zigbee.0 | 2023-07-11 19:41:59.850 | error | Failed to start Zigbee
zigbee.0 | 2023-07-11 19:41:59.849 | error | Starting  zigbee-herdsman problem : "Error while opening serialport 'Error: Error  Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2023-07-11 19:41:44.214 | error | Error herdsman start
zigbee.0 | 2023-07-11 19:41:44.214 | error | Failed to start Zigbee
zigbee.0 | 2023-07-11 19:41:44.213 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"

`

And when i go to the adapter settings it tells me 

You need save and run adapter before pairing!
