### ISSUE TITLE
Cannot get the Node Descriptor of the Device (Timed out after 10000ms)

### ISSUE THREAD

**Issue by valentin38315** [ioBroker/ioBroker.zigbee#202]
Hello,
When trying to pair the Paul Neuheus NLG-RGBW-light all values/instances are here but no one of them work (brightness, colour, state). Does anyone have an idea?

![1](https://user-images.githubusercontent.com/47112999/52919493-4eb64f80-3303-11e9-90b8-00cfe9c8d1db.png)
![2](https://user-images.githubusercontent.com/47112999/52919586-267b2080-3304-11e9-8ded-fa8f39651c99.png)

**Comment by arteck** [comment]
i look for this error also.. same issue with hue, osram, tradfr...

but check this: 

stop the adapter
take the cc2531 out of the machine
then put back in

pairing modus on .. and look again

**Comment by valentin38315** [comment]
oke 👍🏽

**Comment by valentin38315** [comment]
After doing that it comes this error: 
![3](https://user-images.githubusercontent.com/47112999/52966460-aa3a1900-33a7-11e9-92e6-df6fc98d107f.png)

**Comment by larsdecker** [comment]
Wait some minutes before your start the paring process.
The process itself needs some time to start everthing.

**Comment by valentin38315** [comment]
didn't work :(

**Comment by allofmex** [comment]
I experience this problem too.
After replug cc2531 it works again for a while. (restart machine and wait a bit)

What I noticed in this context:
I cannot pair any new devices if cc2531 was running since longer time (> 1hour??). Replug cc2531 is needed. What worsens it is, that some devices seem to periodically refresh there pairing (hue motion sensor, maybe only in case connection was lost for a while, don't know). In that case they stay offline. I have to unplug cc2531, wait until sensor interview finished (no pairing button press needed), then it runs for 1 to 2 days. 
(May this be related to [https://github.com/Koenkk/Z-Stack-firmware/issues/46](url)?)

**Comment by ralfkaminski** [comment]
I got it to run with following steps

1. Start paring mode
2. Scan is running
3. hold down reset Button for 5 seconds until sensors led blinks 3 times
4. press reset Button (short) every 1-2 seconds (you keep the sensor awake)
5. inside the scan Window you can see percentage of object creation

If the error appaears again. repeat the procedure.
good luck
