### ISSUE TITLE
network map move devices

### ISSUE THREAD

**Issue by averlon** [ioBroker/ioBroker.zigbee#2212]
In the network map, you can move devices with your mouse to another position.

Unfortunately, other devices follow! So it is hard to get the map into a view, where all (most) devices don't cover others.

I would like you to think about, if a device is moved, to leave all others at the position they were. The user is then able, e.g. if the user wants to check some specific connections, to move all "disturbing" devices out of view and focus on the devices in question.

**Comment by asgothian** [comment]
linked to issue #2182

**Comment by asgothian** [comment]
Please test by installing from my test branch at
```
https://github.com/asgothian/ioBroker.zigbee/tarball/MapTest
```

I have added a config item to disable physics. Due to the external library used and its functionality, it is advised to not disable physics until the map has been completely drawn at least once. Each time the map is opened (again), physics will be enabled again and this wait time is needed.

I am aware that this is inconvenient, but I see no other option to ensure that the map is being displayed in a meaningful fashion.

A.

**Comment by asgothian** [comment]
A small comment to this functionality: It may be sensible for small / linear maps. Attached is a screenshot of my map. I have played around with the changes for about 45 minutes - it makes absolutely no sense for me, as my map is far too chaotic for this to give any kind of meaning. Note that I have disabled the display of siblings - if those are active too, all you see is tons of lines.

<img width="1011" alt="Screenshot 2024-09-24 at 23 46 17" src="https://github.com/user-attachments/assets/9591dd69-f52e-4254-b2f8-ad14984aecf7">

I an unsure how much time I can sensibly push into this side issue. You are welcome to play around with the library used to display the network. Documentation (in English) including a nice getting started which you can just save as a .html file locally and then run without any Webserver is available [here](https://visjs.github.io/vis-network/).

If you find specific settings which you consider superior to what we have right now I can see to implement those for a test.

A.
