### ISSUE TITLE
New device: IKEA - INSPELNING Smart plug

### ISSUE THREAD

**Issue by Grimes84** [ioBroker/ioBroker.zigbee#2214]
Hi,
the IKEA Smart plug INSPELNING has just been launched in Germany (Europe?).
Nevertheless, I was able to get one. 
On the GIT https://github.com/Koenkk/zigbee2mqtt/issues/23961 you have probably already got it to work. 
On zigbee2mqtt.to only the previous version without current measuring is listed so far.
I still hope that you can get the good piece up and running, at least it's a fairly inexpensive option that you could actually just buy in a store.

Many thanks in advance

Kind regards 
Martin

modelZigbee: INSPELNING Smart plug
type: Router
nwk: 43440
manuf id: 4476
manufacturer: IKEA of Sweden
power: Mains (single phase)
app version: 2
hard version: 1
zcl version: 8
stack version: 114
date code: 20240215
build: 2.4.34
interviewed: true
configured: false

endpoint: 1
profile: 260
input clusters: genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
seMetering (1794)
haElectricalMeasurement (2820)
touchlink (4096)
64636
64645
output clusters:genOta (25)
endpoint:242
profile:41440
input clusters:greenPower (33)
output clusters:greenPower (33)

![INSPELNING](https://github.com/user-attachments/assets/90b6fbf6-f331-411a-83c1-b5ba1373e248)

**Comment by asgothian** [comment]
This will automatically find its way into the zigbee adapter:
- wait until it is part of an official version of the zigbee-herdsman-converters
- wait until this version is linked as dependency in the iobroker.zigbee Adapter.
Done

if you want to be quicker, you can try to get the external converter from that thread to work. In order to do that
- generate a file 'inspelning.js' in the data folder of your zigbee adapter
- paste the code for the external converter inside
- add the filename to the external converter entry in the config
- start the adapter and check the logs if it is actually loaded and used. 

possible required fixes:
- adapt paths to match the path to the respective files of the 'require' statements
- patch the Lib/ikea.js file if it contains items yours does not.

I do not have a plug so I won't be able to do any of that.

A

**Comment by Grimes84** [comment]
Hi,
I installed the instance via your link `https://github.com/asgothian/ioBroker.zigbee/tarball/MapTest`
It is “only” version 1.10.9 available via this link. But that was enough. With this version, the plug can be switched and current measurement also works. At least in my small test with a cell phone charger :)
Nevertheless, thank you very much for your efforts, I would not have expected a working version so quickly.
I would have liked to test it myself as you have described above, but this is a bit beyond my expertise.

Thanks again and keep up the good work.
With kind regards
Martin

**Comment by asgothian** [comment]
Can you please test if you can go back to the stable 1.10.3 version without the adapter crashing at startup ? If so, please also post detail about your coordinator.

To fix it afterwards, just return to the MapTest version

A.

**Comment by Grimes84** [comment]
When I get back from work, I'll be to test it.
