### ISSUE TITLE
SONOFF SWV (smart water valve) - Datenpunkt available/Verbindungsabbruch wird nicht dargestellt und bleibt immer auf "True" (Batterien entfernt)

### ISSUE THREAD

**Issue by Sweatchuck** [ioBroker/ioBroker.zigbee#2332]
### Tested with adapter version

v1.10.13

### modelZigbee

SWV

### manufacturer

SONOFF

### Link to device

https://www.zigbee2mqtt.io/devices/SWV.html

### Coordinator type selected in adapter setting

zStack3x0

### Coordinator

Sonoff Zigbee 3.0 USB Dongle Plus / Aeotec WG001 RangeRange extender

### Coordinator firmware version and revision

2-1.2.7.1.;20210708

**Comment by Sweatchuck** [comment]
Verbindungsabbruch wird nicht dargestellt. Schalter zeigt an obwohl das Gerät nicht erreichbar war. Fehlermeldung im Protokoll vorhanden.

**Comment by asgothian** [comment]
Das System kann nicht erkennen das das Gerät nicht vorhanden ist, da es durchaus zulässig ist das batteriebetriebene Geräte über eine längere Zeit keine Nachrichten senden. Und ab dem Moment wo die Batterien leer sind / raus sind kommen halt keine Nachrichten mehr

**Comment by Sweatchuck** [comment]
Das sehe ich anders. Es müsste im ioB ja als nicht erreichbar (wie z.B. bei Homematic) dargesrellt werden. Wenn es z.B. durch irgendwelche Effekte abgeschirmt wurde und ich im ioB auf ON stelle geht der „Schalter“ auf ON obwohl das Ventil nicht geschalten hat. Wenn das Gerät also kein Feedback liefert (ich bin an - bidirektional) darf der Schalter nicht auf ON gehen und müsste available auf false setzen.

**Comment by asgothian** [comment]
Wenn du den Datenpunkt korrekt anschaust dann wirst du sehen das die Anforderung auf "wahr" nicht bestätigt wird. Damit bekommt der ioBroker mit das der Befehl ggf. nicht ausgeführt wurde. So ist das meines Wissens im ioBroker vorgesehen, und wird auch so genutzt.

Da es verschiedene Gründe geben kann warum ein Gerät einen Befehl nicht bestätigt wurde entschieden den 'available' status **nicht** anzupassen wenn eine Nachricht nicht durchgeht. Das ist also 'by design'. Wenn du Nachhalten willst ob Befehle ausgeführt werden solltest Du auf die Bestätigung im Objektbaum reagieren.
