### ISSUE TITLE
aqara WXKG12LM

### ISSUE THREAD

**Issue by Thomas1305** [ioBroker/ioBroker.zigbee#272]
hi guys,
after pairing the switch shows onyl following stats.
![image](https://user-images.githubusercontent.com/46224531/55000791-90f24100-4fd3-11e9-8d5e-4c505eac2129.png)

I´m missing shake, hold, release

**Comment by Thomas1305** [comment]
so i guess nobody has this switch?

**Comment by asgothian** [comment]
I have seen the issue, but i cannot fix it at this time. But it is on the list.

**Comment by Thomas1305** [comment]
Thx
Maybe i can help you?

**Comment by asgothian** [comment]
In order to do that you need to fork the adapter and check how shake, hold and release are set in the zigbee-Shepherd-converters and then see if a matching state exists in the states mapping. If so, you can link that state to the entry for the switch and test the changes.
I should be on the iobroker ts tomorrow afternoon/early evening if you want to give it a try.

A.

**Comment by Thomas1305** [comment]
Sorry, i've never done this before.
Is there a guidance available how to do this?

**Comment by asgothian** [comment]
I haven't found one - just dug my way through the whole stuff to see how it fits together when i started with it.

**Comment by Thomas1305** [comment]
@asgothian 
do you need any help now?
