### ISSUE TITLE
Add support for OSRAM SMART+ Motion Sensor (occupancy and temperature)

### ISSUE THREAD

**Issue by c-you-lexe** [ioBroker/ioBroker.zigbee#354]
It would be great to have support for OSRAM SMART+ Motion Sensor (occupancy and temperature)
https://secure-web.cisco.com/1GAMY_-4NiPOPJWwrAgvf6yM22P-f9yRS_MbLRa115_lIV2B0MKK2NXDeK0WMeS_E2S4nZAlrpq7QYJ25jZAyVwYpSIu0FQlbbwy9GAFCtLOBvUr-bBE_bvjyj4AS2ZYH5X_BYLFdO3uDRXOp_TpJV-zBxIVVW18d5M4TyGHsfDfz7MjJn-eksDulTUqlPR0UA80qT4Uq8jQvDllck7m9lywEff-cyMN7bkQMjn0MXHw/https%3A%2F%2Fwww.zigbee2mqtt.io%2Fdevices%2FAC01353010G.html

**Comment by BoBeRzE** [comment]
For me its not possible to pair the motion sensor. i always get:

Cannot get the Node Descriptor of the Device: 0x000d6f000e05b0ad (Error: Timed out after 10000 ms)

My Device is: AC01353010G | x2417

**Comment by killakaktus** [comment]
Same here.

**Comment by c-you-lexe** [comment]
@BoBeRzE and @killakaktus:
That's the reason why I would politly asked for adding support to iobroker.zigbee.
In Zigbee2mqtt is already support for the OSRAM SMART+ Motion Sensor and according to the readme it should not be that much effort to add the support for this great devices to iobroker.zigbee as well.
If someone could tell me how (probably there is some documentation available) I would appreciate to do it myself.

**Comment by allofmex** [comment]
As @BoBeRzE and @killakaktus said and as mentioned in https://github.com/ioBroker/ioBroker.zigbee/issues/219, the problem is not the "support" in zigbee adapter but that the Osram Sensors is not pairing with our cc2531 sticks at all. Zigbee-adapter is not yet involved at this step.

You may try it yourself. If you find a reliable way to pair the sensor until it shows as device card with question-mark icon (= not yet supported device), then we have a chance. No device specific support needed for this.

**Comment by c-you-lexe** [comment]
My fault, sorry. And thank you for the explanation.
