### ISSUE TITLE
Osram Gardenspot W not responding

### ISSUE THREAD

**Issue by chr-jordan** [ioBroker/ioBroker.zigbee#374]
Gardenspots W are found as a device but not reacting on changing object values.

**Comment by asgothian** [comment]
Please be more specific with the error message:
- how does it look in the object tree ?
- how does it look in the adapters list of devices ?
- what happens if you press the litte i icon for the gardenspot on the adapters list of devices

"... don't work" is not an error message anyone can work with.

**Comment by chr-jordan** [comment]
The device appears simply with available "false". Changing values like brightness and state have no effect.
![Bildschirmfoto_2020-03-22_07-38-26](https://user-images.githubusercontent.com/44375264/77243992-8e3f2180-6c10-11ea-8017-496410940602.png)
