### ISSUE TITLE
Stack 3 Firmware CC2531_20190425 devices offline after restart

### ISSUE THREAD

**Issue by allofmex** [ioBroker/ioBroker.zigbee#380]
Anyone running Koenkk's  [Stack 3 Firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x/bin) with zigbee adapter?

First it works: Adapter starts, pairing ok, devices work as expected.

But: If I **restart** adapter or whole system, all devices do not rejoin the network and stay offline. (tested with hue smart swich, dimmer switch and gu10 ambiance)

Did anyone else tested stack 3 firmware?

@kirovilya not sure how far you are with the [zigbee-herdsman](https://github.com/ioBroker/ioBroker.zigbee/tree/herdsman) changes: If it works there, we can wait until we are ready to switch to herdsman and stay with stack 1.2 so far.

**Comment by kirovilya** [comment]
We used Z-stack 3 together with cc2538.
We found a problems together with @arteck in the shepherd when working with stack 3 - and made a patch that push into the heardsman and our shepherd-fork - came out in iob.zigbee 0.11.3
It just appeared when the adapter/system was restarted.

The problem with firmware 3.0 is that there is no prohibition on changing panID in case of network conflict. This problem was resolved in 1.2 https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/firmware.patch#L121 , but not resolved in 3.0 by Koen.
For cc2538 firmware we also made such a hack.
With the firmware hack and the shepherd patch that you can work with the 3.0 stack.

About the new herdman... a lot has changed there.
I started a branch in the adapter to rewrite it, but there is not enough time.

**Comment by Xsev1** [comment]
Hello,
My coordinator lost connection after each reboot too (reproducible).
I tested on my own server an a second installation by a friend. We run the maxstability 20190315 whitout problems for some months. After upgrade 20190610, you can pair everything, all ok but after rebooting your server the zigbee never connect again.
Testet hardware and versions:
-CC2531 Pi + Nuc (Debian) ioBroker
-CC2530-2591 Pi ioBroker
-Home1.2
-Source Routing 1.2
-Z-stack3

The new coordiantor firmware works fine at beginning but if i restart my server, it lost connection and i must repair the complete Network. This bug i had never before with an older coordinator firmware.
Thats a very big problem for me.

**Comment by kirovilya** [comment]
I do not use firmware with source routing, but I think that such problems with 1.2 should not be observed.
what version of iob.zigbee adapter? try downgrading?

**Comment by kirovilya** [comment]
For z-staсk a similar error appeared when the coordinator detected a dublicate/conflict of panId - then it moved on to the next and all the devices fell off. But this was fixed in the firmware (default home 1.2).
So very strange...

maybe you have several coordinators nearby on the same panID and channel? try changing the panid or channel

**Comment by antst** [comment]
BTW, what we fixed in Z-stack 3.0 firmware, I am not sure it is fixed in Koen firmware.
