### ISSUE TITLE
Adapter verliert Verbindung zu XiAOMI

### ISSUE THREAD

**Issue by soRailicious** [ioBroker/ioBroker.zigbee#395]
Leider verliert der Adapter nach Zeitraum X die Verbindung zu xiamio / aqana Hardware. Die Position des Sticks als auch der Hardware wurde nicht verändert. Geräte werden zwae angezeigt, aber die Werte verändern sich nicht mehr. Ich habe bereits den Raspberry als auch ioBroker bzw. den zigbee neugestartet und leider bekomme ich nach wie vor keine Verbindung. Im iobroker log finde ich keine Informationen woran es liegen könnte... Wie kann ich dem Problem auf die Spur kommen? Muss ich wirklich ein xiami gateway kaufen damit ich keine Probleme mehr habe?

**Comment by arteck** [comment]
mit deiner Problembeschreibung kann ich nix anfagen.. ein "es hat sich nix geändert" und "der Adapter verliert die Verbindung" bringt mich nicht weiter.. somit kann ich dir nicht helfen..

**Comment by soRailicious** [comment]
Hallo, naja der Status der Sensoren, in diesem Fall eines aqara fenster Kontaktes bleibt auf einmal auf false egal ob das stimmt oder nicht. Ich kann mit dem Problem auch nichts anfangen, sonst hätte ich hier nix geschrieben! Es scheint ja so als würde die Verbindung ohne physische Einflüsse zwischen Stick und Sensor abbrechen. Jetzt ist die Frage wie man dem auf die Spur kommt... Ich vertraue da auf eure expertise. Ein "kann ich nix mit anfangen" ist nicht hilfreich für den Ansatz ein Problem zu lösen oder?

**Comment by arteck** [comment]
hast du mal im forum dich mal belesen.. wie ein zigbee funktioniert und was für Probleme auftreten können.. expertise hin oder her aber .. ohne eindeutige Fehler beschreibung wird das nix..

**Comment by soRailicious** [comment]
Den Fehler habe ich bereits 2x beschrieben oder sehe ich das falsch? Welche Informationen benötigst du noch damit wir ggf gemeinsam eine Lösung finden?

**Comment by 10Tman** [comment]
Maybe I can shed some more light onto this. I have a network of about 30 ZigBee routers and end devices (Xaiomi Aqara and IKEA) and know the problem of Aqara sensors not reporting any more readings after working perfectly for days or weeks. 
I am running version 0.11.5 of the adapter together with a CC2531 based  USB stick running the ZStack firmware 2.6.3 rev 20190425 (the HA1.2 firmware by Koenkk).

Today my lumi.weather sensor stopped reporting data and I used a ZigBee sniffer to check out what is going on in my network. I can see the sensor (EUI64: 00158d000321e483, NWK address:0x54C2) reporting temperature, humidity and pressure periodically to the Coordinator (the USB stick) via a router. The Coordinator is sending a MAC Acknowledgement on receipt of the reports, so it definitely receives the messages. The corresponding objects in IObroker are not getting updated though.

Next I switched the debug level of the Zigbee adapter to "debug" and looked at the logs. Initially there was no mention of 00158d000321e483 in the logfile. When triggering a build of the network map in the adapter I am finding the following in the logs:

2019-12-08 19:56:59.847 - info: zigbee.0 (11552) 9 (0x00158d000321e483): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)

So we remember the device which is good, but then I am also getting

2019-12-08 19:56:59.798 - debug: zigbee.0 (11552) Current active devices:
(...)
2019-12-08 19:56:59.821 - debug: zigbee.0 (11552) {"type":"EndDevice","ieeeAddr":"0x00158d000321e483","nwkAddr":20273,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"status":"online","joinTime":1575831419}
(...)

The listed network address of 20273 is 0x4F31, however as I saw in my over the air capture the actual network address of the sensor is 0x54C2. So I suspect the sensor changed its network address and the adapter didn't get to know. A ZigBee device could change its network address for legitimate reasons, like an address conflict or change of parent. The latter is most likely with the Aqara sensor as it is very sleepy and some routers don't like that. 

So what I think should happen is that on the adapter there should be a way to gain knowledge of a device changing its network address. For example when building the network map the coordintor is sending out LQI table requests and the parent router of the troublesome sensor is correctly responding with the correct and updated network address next to the EUI64. This and potentially other data (device announce, if sent at all) could be used to repair whatever table contains the old invalid network address of the sensor. 

This is actually my first post here and I am still relatively new to IoBroker and this adapter. I am aware that the issue may also be caused by a lower layer like the CC2531s firmware itself, but hopefully this information is useful for some of the guys here. Let me know if I can provide any additional data which might be of use.
Apart from the periodic dropping of Aqara sensors I am super happy with my setup!

**Comment by allofmex** [comment]
>  I suspect the sensor changed its network address and the adapter didn't get to know

@10Tman sounds like problem reported in [Enddevices unreachable because route not updating](https://github.com/Koenkk/zigbee2mqtt/issues/1408)

You are right, the parent address is in some cases not updated correctly. It is a problem in Zigbee stack 1.2 if source_routing is enabled. Only option is, not to use source_routing.

Please update your cc2531 to latest **default** firmware. 
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin
Source_routing is not fully disabled there too, but it is limited to one (fast-aging) routing entry, that will be replaced frequently.

**Comment by 10Tman** [comment]
Thanks @allofmex. This indeed sounds like it is the issue here.
I will give this a try over the Christmas break and report back how it went.

**Comment by Gwoony** [comment]
Hallo leider ist es bei mir auch so. (Branch Herdsman). Die Geräte werden angezeigt, aber die States bleiben leer. Und ich weiss nicht warum..

**Comment by soRailicious** [comment]
Hey, bei mir hat es sich beruhigt, nachdem ich den Kanal gewechselt und alle Geräte neu angelernt habe!
