### ISSUE TITLE
Support for CC1352P-2 and CC26X2R1

### ISSUE THREAD

**Issue by vain90** [ioBroker/ioBroker.zigbee#415]
Koenkk listes the two dev boards Texas Instruments CC26X2R1 and CC1352P-2 as "supported adapters" on his zigbee2mqtt website.
https://www.zigbee2mqtt.io/information/supported_adapters.html

Do these also work with the Zigbee adapter in the ioBroker?

**Comment by kirovilya** [comment]
I think yes #387

**Comment by xengosam** [comment]
Hi @kirovilya,
first of all, thanks for that great adapter!

I am trying to move all zigbee devices to the TI dev board CC1352P-2, but now I am facing some problems.

It seems that something with the port is not right .. the old cc2531 is working with the new herdsman Version.

Hope you can help me.. you can find the log of the adapter start attached.

Thanks!

[Log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3870894/Log.txt)

**Comment by kirovilya** [comment]
"Cannot lock port" - I see that error when often restart adapter... but after next restart it was ok

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/2315

**Comment by xengosam** [comment]
Ok yes, but I think that the error below is causing the adapter to restart .. 
So the main error I get is this: **Error: SRSP - SYS - version after 6000ms**

Have you any idea what I can do to make it run?

[Log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3872965/Log.txt)

**Comment by kirovilya** [comment]
maybe something else is blocking the port...
@J-Paul0815 Can you help with CC1352P-2 and CC26X2R1 ?

**Comment by xengosam** [comment]
So I played a little bit with the CC1352P-2 and flashed it this time with SmartRF Flash Programmer 2 .. In this Software I also got a new firmware update for this board and now the **error is gone**! 

I also changed the PanID to ensure that nothing from the old network is not blocking the new one..

The zigbee adapter is green and I tried to pair also some of my devices… The improvements of pairing sensors like Xiaomi door sensor and Temperature sensors are great! Thank you for that!

I only receive an error with my smoke sensor .. do you have any idea what's the problem is? Before the update and switch to this board, I also received that the device could not be configured .. 

[Log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3875421/Log.txt)

**Comment by arteck** [comment]
Smoke sensor is s other issue
