### ISSUE TITLE
Philips HUE RWL021

### ISSUE THREAD

**Issue by mdberlin01** [ioBroker/ioBroker.zigbee#44]
Philips HUE RWL021 is detected in the iobroker and displayed under Objects. Unfortunately, when pressing the buttons on the remote control no reaction in the iobroker. Under zigbee2mqtt the remote control can be operated correctly. Is it possible to repair this at ioBroker.zigbee so that Philips HUE RWL021 can be used in iobroker.

Sincerely

**Comment by arteck** [comment]
My 2 rwl021 works perfect..

**Comment by arteck** [comment]
i bought today a new one..and now a have a same problem..
https://github.com/Koenkk/zigbee2mqtt/issues/422

**Comment by Garfonso** [comment]
I have a similar issue. Sometimes RWL021 works, but it is very unreliable and after a short while is not working anymore and than needs to be paired again.

**Comment by Curtis777** [comment]
After many days I got it working...
I had the same problem pairing was possible but didn't create any states... 
I resset it by pressing all 4 buttons and hold till the red light flash. 
And then the pairing mode on the remote starts... 
I reboot my iobroker and worked fine

**Comment by Garfonso** [comment]
I always did reset it using the button in the back.
For me it now works fine since I upgraded my PI B to a PI 3 and completely reinstalled this host (in a multi host IoBroker system). I then copied old sheperddb to avoid having to re-pair everything and re-paired the remote once more and now it works fine.
