### ISSUE TITLE
Coordinator on red

### ISSUE THREAD

**Issue by Stoimie** [ioBroker/ioBroker.zigbee#444]
Hi, I have a problem, the coordinator in my map is always displayed in red, although there are active connections and they are displayed in green. However, I find the connection quality rather poor, although the sensors are less than 2m away. I connected the USB stick to the Raspberry with a 2m cable. The teach-in also only works after countless attempts. I already ordered a new stick in the hope that it is a hardware problem. Has anyone else had this problem?

<img width="522" alt="Bildschirmfoto 2019-12-17 um 20 50 12" src="https://user-images.githubusercontent.com/11144890/71033929-91f67000-2118-11ea-9fd1-bf2a6bd0009f.png">

**Comment by nob0dy80** [comment]
@Stoimie 

you use a 2m usb extension cable to connect your zigbee stick ? do i get that right?
the coordinator seems to be displayed in red if a device is directly connected with a poor signal.

Ordering an other stick will **not** fix this.

You can try to connect the stick directly to the usb port. Using an extension cable is for active devices mostly a bad idea. It can work, but it doesnt have to. 

Instead of buying a new stick, i would have bought a device that is capable of being a router like a smart plug or a hue light. 
If you put the lumi cube near the coordinator for a day and the signal strengh is still 1, i guess that something is wrong with the cube and not with the coordinator. I'm guessing this cause your other devices have a good connection at all.
