### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.zigbee#560]
I see the following errors in log. This happen right after script requested certain lights to go off based on schedule (23:30) function. Please advise what is going on, if I need to be concern over this message.
![image](https://user-images.githubusercontent.com/19657413/76722355-9b907380-6719-11ea-8f5b-45bad330114f.png)
I am running Linux on Intel X64 platform with zigbee adapter version 1.1.1, latest node.js, controller, etc.
Thank you

**Comment by BigMike71** [comment]
ive have the same errors since 2 weeks :(


zigbee.0 | 2020-04-16 07:12:53.082 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
-- | -- | -- | --
zigbee.0 | 2020-04-16 07:12:53.082 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-04-16 07:12:53.082 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:23)
zigbee.0 | 2020-04-16 07:12:53.082 | error | (13843) Error on send command to 0x7cb03eaa0a03f37e. Error: Error:  Command 0x7cb03eaa0a03f37e/3 genOnOff.off({},  {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":false})  failed (Erro
zigbee.0 | 2020-04-16 07:12:29.857 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee.0 | 2020-04-16 07:12:29.857 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-04-16 07:12:29.857 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:23)
zigbee.0 | 2020-04-16 07:12:29.857 | error | (13843) Error on send command to 0x7cb03eaa0a03f37e. Error: Error:  Command 0x7cb03eaa0a03f37e/3 genOnOff.on({},  {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":false})  failed (Error

**Comment by arteck** [comment]
check new version

**Comment by apla2016** [comment]
Hello arteck, do I need to load new version from github? It is not yet available from ioBroker.
Thank you!

**Comment by apla2016** [comment]
> check new version

Where can I get new version?

**Comment by apla2016** [comment]
Latest version of zigbee adapter #1.1.1 acts exactly the same, I see no changes.

**Comment by apla2016** [comment]
This issue hasn't been fixed, so why are you closing it?

**Comment by apla2016** [comment]
This issues hasn't been fixed, please don't close it

**Comment by Tschipel** [comment]
When using an Aqara PIR, which is switching an IKEA Floalt panel on via blockly script i get these errors. The function - switch on the panel - is given.

2020-08-28 20:25:31.681  - error:  zigbee.0 (6960) Error on send command to 0x14b457fffe40f52d. Error:  Error: Command 0x14b457fffe40f52d/1 genOnOff.on({},  {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false})  failed (Error: Data request failed with error: 'No network route'  (205))
--
at Endpoint. (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:339:23)
at Generator.throw ()
at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)

**Comment by asgothian** [comment]
> Error: Data request failed with error: 'No network route' (205)

This error refers to the fact that the zigbee network does not know where to send the command to. Please verify
- can you manually switch the floalt panel ?
- is it listed as "available" in the object list ?
- does it show up as connected in the network map
- can you please post log snippets in code tags for readability.

Also: Please do not reuse existing issues with possibly different error messages.

>This issues hasn't been fixed, please don't close it

- does the issue remain in the current 1.2.1 version ?
- can you please post the complete log lines as text (in code tags), not as screenshot ? The information in the screenshot is incomplete. Most importantly, the actual reported error is missing in the screenshot.
