### ISSUE TITLE
CC2530 als Slave

### ISSUE THREAD

**Issue by erwin23** [ioBroker/ioBroker.zigbee#59]
Hallo,
Habe neben dem CC2531 als Master auch einen CC2530 als Slave installiert.
Die Kommunikation der gepairten Geräte am CC250 funktioniert.
Nur im iobroker wird beim CC230 unter Switch State "false" eingetragen.
Somit kann man die Kommunikation nicht überwachen.
Beste Grüße

**Comment by modmax** [comment]
What is the expected behaviour?
I think that the CC2530 (which is recognized as lumi.router) has no switch state.
I think that the switch state is just present to have a device in the object tree view.

What should the surveillance of the CC2530 do? I only can think of some diagnostics shoch can be turned off or on .. but that's justz a suggestion.

**Comment by allofmex** [comment]
No response, closing.
