### ISSUE TITLE
promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

### ISSUE THREAD

**Issue by sam-75** [ioBroker/ioBroker.zigbee#681]
My CC was hanging and offline, after reboot all devices are offline.
Also if i change channel. 
Is a channel change = rebind all devices ? 

Further if i click on devices the adapter crashes with

promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
(22947) unhandled promise rejection: Cannot read property 'mapped' of undefined
--
(22947) TypeError: Cannot read property 'mapped' of undefined
--
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:304:36)
--
at processTicksAndRejections (internal/process/task_queues.js:97:5)
--

what can I do on 20+ devices it is really a mess to rebind them all ... 
An my scipts won´t work anymore... :(

**Comment by arteck** [comment]
which cc ??

**Comment by Shadesh** [comment]
Got the same error now two times in two days. My devices came back but the zigbee process restarted.
I have 3x CC2531 as router and 1x as coordinator.

**Comment by LittleNo** [comment]
I see the same error after upgrading to 1.20, here's the full log:

`

host.raspberrypi | 2020-08-15 16:05:13.224 | info | instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
zigbee.0 | 2020-08-15 16:05:12.425 | info | (6726) Terminated (NO_ERROR): Without reason
zigbee.0 | 2020-08-15 16:05:12.421 | info | (6726) terminating
zigbee.0 | 2020-08-15 16:05:12.288 | error | (6726) TypeError: Cannot read property 'id' of undefined at StatesController.syncDevStates (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:280:27) at process._tickCallback
zigbee.0 | 2020-08-15 16:05:12.287 | error | (6726) unhandled promise rejection: Cannot read property 'id' of undefined
zigbee.0 | 2020-08-15 16:05:12.286 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:05:12.156 | error | (6726) TypeError: Cannot read property 'prop' of undefined at statesMapping.commonStates.concat.devStates.states.filter (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:309:85)
zigbee.0 | 2020-08-15 16:05:12.155 | error | (6726) unhandled promise rejection: Cannot read property 'prop' of undefined
zigbee.0 | 2020-08-15 16:05:12.154 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:05:12.092 | info | (6726) Zigbee: disabling joining new devices.
zigbee.0 | 2020-08-15 16:05:12.088 | info | (6726) cleaned everything up...
zigbee.0 | 2020-08-15 16:05:12.086 | error | (6726) TypeError: Cannot read property 'prop' of undefined at statesMapping.commonStates.concat.devStates.states.filter (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:309:85)
zigbee.0 | 2020-08-15 16:05:12.085 | error | (6726) unhandled promise rejection: Cannot read property 'prop' of undefined
zigbee.0 | 2020-08-15 16:05:12.084 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:05:12.073 | info | (6726) Zigbee started
zigbee.0 | 2020-08-15 16:05:12.071 | info | (6726) 0xec1bbdfffe6fd246 (addr 25354): RB 250 C - Innr E14 bulb RGBW (Router)
zigbee.0 | 2020-08-15 16:05:12.069 | info | (6726) 0x680ae2fffe3dbd87 (addr 61107): ICZB-IW11D - iCasa ZigBee AC dimmer (Router)
zigbee.0 | 2020-08-15 16:05:12.067 | info | (6726) 0xec1bbdfffe6fd556 (addr 29137): RB 250 C - Innr E14 bulb RGBW (Router)
zigbee.0 | 2020-08-15 16:05:12.064 | info | (6726) 0x7cb03eaa0a085a73 (addr 14459): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2020-08-15 16:05:12.057 | info | (6726) 0xd0cf5efffebde4dd (addr 6258): LED1545G12 - IKEA TRADFRI LED bulb E26/E27 980 lumen, dimmable, white spectrum, opal white (Router)
zigbee.0 | 2020-08-15 16:05:12.046 | info | (6726) Currently 5 devices are joined:
zigbee.0 | 2020-08-15 16:05:12.031 | info | (6726) --> transmitPower : normal
zigbee.0 | 2020-08-15 16:05:12.016 | info | (6726) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20181024}}
zigbee.0 | 2020-08-15 16:05:09.654 | info | (6726) Starting Zigbee...
zigbee.0 | 2020-08-15 16:05:09.646 | error | (6726) Serial port not selected! Go to settings page.
zigbee.0 | 2020-08-15 16:05:09.547 | info | (6726) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.21.0, js-controller: 3.1.6
host.raspberrypi | 2020-08-15 16:05:05.291 | info | instance system.adapter.zigbee.0 started with pid 6726
host.raspberrypi | 2020-08-15 16:04:34.946 | info | Restart adapter system.adapter.zigbee.0 because enabled

`

Going back to the official 1.0.4 makes everything working again.

**Comment by kirovilya** [comment]
@LittleNo fixed. try to install from github

**Comment by LittleNo** [comment]
thanks, but it's still the same:

`

host.raspberrypi | 2020-08-15 16:31:14.150 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-08-15 16:31:14.149 | info | instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
zigbee.0 | 2020-08-15 16:31:13.358 | info | (9018) Terminated (NO_ERROR): Without reason
zigbee.0 | 2020-08-15 16:31:13.355 | info | (9018) terminating
zigbee.0 | 2020-08-15 16:31:13.186 | error | (9018) TypeError: Cannot read property 'id' of undefined at StatesController.syncDevStates (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:280:27) at process._tickCallback
zigbee.0 | 2020-08-15 16:31:13.185 | error | (9018) unhandled promise rejection: Cannot read property 'id' of undefined
zigbee.0 | 2020-08-15 16:31:13.184 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:31:13.079 | error | (9018) TypeError: Cannot read property 'filter' of undefined at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:309:30) at process._tickCall
zigbee.0 | 2020-08-15 16:31:13.078 | error | (9018) unhandled promise rejection: Cannot read property 'filter' of undefined
zigbee.0 | 2020-08-15 16:31:13.077 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:31:12.931 | info | (9018) Zigbee: disabling joining new devices.
zigbee.0 | 2020-08-15 16:31:12.927 | info | (9018) cleaned everything up...
zigbee.0 | 2020-08-15 16:31:12.925 | error | (9018) TypeError: Cannot read property 'filter' of undefined at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:309:30)
zigbee.0 | 2020-08-15 16:31:12.924 | error | (9018) unhandled promise rejection: Cannot read property 'filter' of undefined
zigbee.0 | 2020-08-15 16:31:12.924 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-08-15 16:31:12.912 | info | (9018) Zigbee started
zigbee.0 | 2020-08-15 16:31:12.910 | info | (9018) 0xec1bbdfffe6fd246 (addr 25354): RB 250 C - Innr E14 bulb RGBW (Router)
zigbee.0 | 2020-08-15 16:31:12.908 | info | (9018) 0x680ae2fffe3dbd87 (addr 61107): ICZB-IW11D - iCasa ZigBee AC dimmer (Router)
zigbee.0 | 2020-08-15 16:31:12.906 | info | (9018) 0xec1bbdfffe6fd556 (addr 29137): RB 250 C - Innr E14 bulb RGBW (Router)
zigbee.0 | 2020-08-15 16:31:12.903 | info | (9018) 0x7cb03eaa0a085a73 (addr 14459): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2020-08-15 16:31:12.896 | info | (9018) 0xd0cf5efffebde4dd (addr 6258): LED1545G12 - IKEA TRADFRI LED bulb E26/E27 980 lumen, dimmable, white spectrum, opal white (Router)
zigbee.0 | 2020-08-15 16:31:12.885 | info | (9018) Currently 5 devices are joined:
zigbee.0 | 2020-08-15 16:31:12.870 | info | (9018) --> transmitPower : normal
zigbee.0 | 2020-08-15 16:31:12.855 | info | (9018) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20181024}}
zigbee.0 | 2020-08-15 16:31:10.465 | info | (9018) Starting Zigbee...
zigbee.0 | 2020-08-15 16:31:10.451 | error | (9018) Serial port not selected! Go to settings page.
zigbee.0 | 2020-08-15 16:31:10.324 | info | (9018) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.21.0, js-controller: 3.1.6
host.raspberrypi | 2020-08-15 16:31:06.193 | info | instance system.adapter.zigbee.0 started with pid 9018

`

**Comment by kirovilya** [comment]
@LittleNo oh sorry, try to fix again. update again please

**Comment by LittleNo** [comment]
now it works, great!
