### ISSUE TITLE
Cannot delete devices

### ISSUE THREAD

**Issue by haumichel** [ioBroker/ioBroker.zigbee#764]
Hi,
if I try to delete devices in the zigbee adapter for iobroker I get the following error message:

(25815) Failed to remove TypeError: Cannot read property 'stack' of undefined at ZigbeeController.remove (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:358:65)

Thanks for your help

**Comment by Much2k** [comment]
I have the same problem with switching to a Conbee II adapter. Wanted to delete a device because it was not paired properly. Then he spits out this error message. Zigbee Stable Adapter 1.2.1
![Unbenannt](https://user-images.githubusercontent.com/71147342/92956276-e8ee6300-f466-11ea-8740-3e3ad436f48f.PNG)

**Comment by Much2k** [comment]
If you press the Touchlink Reset, the system also crashes
![Unbenannt](https://user-images.githubusercontent.com/71147342/92958306-4637e380-f46a-11ea-98cd-a4077d90f8bd.PNG)
