### ISSUE TITLE
Wrong link quality with Conbee 2

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.zigbee#773]
When I first started to use the conbee 2 I noticed that my link quality was really bad on all devices like 0-5, the next day it was 20-30 next day 50-60 and it will continue like this for 1 or 2 weeks until it reaches the max value of 255 and then starts over at 0 again :) 

So I doubt the link quality is meaningful at all in the current state,

**Comment by Sascha79** [comment]
I can see the same problems with my installation.

**Comment by BernhardLinz** [comment]
Have the same Problem, have values from 1 to 4, 1 looks like good quality, 5 for bad

**Comment by schmidti2007** [comment]
Yip, same for me. Was wondering why all new devices started with 5. After 30 min they were at 7... I will keep an eye on this, just binded few hours ago...

**Comment by BernhardLinz** [comment]
I updated my Conbee II to the latest Firmware (0x26580700 from 2019) because i ahd have also a problem with losing connection to some Devices (and i thought the newest was installed but i was wrong).

Now all devices have values of 220 up to 226 for Link Quality - regardless of their distance from the USB stick.
short time after the update the calues where 60 to 78, then every time the new value seams to be added up the values now of 220 to 226. Sometimes the value go one up or down.

I think these values are also wrong.

**Comment by trollvottel** [comment]
Still an issue
