### ISSUE TITLE
Please add Gledopto zigbee adapter

### ISSUE THREAD

**Issue by igitlin** [ioBroker/ioBroker.zigbee#79]
Please add support GLEDOPTO Zigbee adapter for LED Stripe
this adapter has a many types 
RGB
RGBW
RGBCCT
WWCW
Dimmer
https://ru.aliexpress.com/item/G-OPTO-ZIGBEE-RGB-CCT-WW-CW/32858603964.html

**Comment by arteck** [comment]
done

**Comment by kirovilya** [comment]
Some types added in 0.8.0 version. Check out please

**Comment by obodeldog** [comment]
Hi! 
I tested this one: https://www.aliexpress.com/item/GLEDOPTO-LED-ZIGBEE-12W-RGB-CCT-bulb-AC100-240V-RGB-and-dual-white-e27-e26-dimmer/32906939699.html?spm=a2g0s.9042311.0.0.40d14c4dSq2UmY

The device was found:

<img width="506" alt="2018-12-28 17_17_55-iobroker admin" src="https://user-images.githubusercontent.com/35403739/50521148-90293c00-0ac4-11e9-8eaa-fd261d6fc496.png">

But there are no devices in "Objekte" -> "zigbee".
Since this is my first Zigbee device, I would like to know if the objects should normally appear here?
