### ISSUE TITLE
state of devices & group are not in sync

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.zigbee#831]
I have a small group with 2 HUE bulbs. When switching the group on all bulbs are switched on.

But the state of those 2 bulbs in ioBroker is still "false". So it dosen't represent the real state of the device. (same with other options like colortemp)

**Comment by vain90** [comment]
Please fix that. Thats really annoying with scenes.

**Comment by asgothian** [comment]
Fixing this requires a massive fix in the zigbee-herdsman-converters. All Lightbulbs need to be configured to report the state change to the coordinator. This is not currently the case. Without this change, fixing the issue becomes very difficult.

A.

**Comment by kirovilya** [comment]
It needs to be rework groups and do like z2m. https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/groups.js

**Comment by asgothian** [comment]
There is an alternative: As of now, it seems that groups are only supported for lights, always exposing the states brightness, color, colrotemp, state and transition_time to the user.

Upon joining a group, it should be possible to attempt to configure the reporting of the attached device to update the first 4 automatically when they change. This would generate the requested solution with a minimum of extra fuss, although it would limit functionality to devices which support status reporting.

I am currently testing status reporting with:
- ikea transformers and lightbulbs,
- different Hue lightbulbs
- two kinds of NUE dimmers
- Osram Plugs
- Tuya compatible plugs

A.

**Comment by asgothian** [comment]
I have a test version of the adapter which can be installed from 
https://github.com/asgothian/ioBroker.zigbee/tarball/Groups 
This version should at least partly fix this issue.

Partly because:
- Sync of color and colortemp may not work as expected
- Sync of brightness will be incorrect when the group has a transition time set
- Not all group members may support the required functionality. I have not found any which do not, but the number of different devices this was tested is very limited (to the devices i actually own)

Once testing is complete, the functionality of said branch will be integrated into the main adapter.

A.

**Comment by asgothian** [comment]
Fixed in 1.4.6, closing
