### ISSUE TITLE
VisorTech NX6407-944 in Zigbee-Adapter

### ISSUE THREAD

**Issue by Jean-GO** [ioBroker/ioBroker.zigbee#912]
Hallo,

währe es möglich, den Türgriff von VisorTech (NX6407-944) mit in den Adapter einzubinden?

ich möchte ungerne die cloude nutzen, aber in Zigbee-Adapter ist dieser leider nur als Fragezeichen sichtbar.

Grüße und guten Rutsch

**Comment by asgothian** [comment]
- did you check if it is listed in the zigbee-herdsman-converters
- can you post the tile from the config page as well as the page coming up on info when the lock is paired ?
A

**Comment by Jean-GO** [comment]
![Bild_01](https://user-images.githubusercontent.com/76437060/103237977-966b8080-4949-11eb-932b-fc9ebebd00bf.JPG)
![Bild_02](https://user-images.githubusercontent.com/76437060/103237978-979cad80-4949-11eb-941e-b814477172f4.JPG)

**Comment by asgothian** [comment]
please make a pull request on koenkk/zigbee-herdsman-converters. Once it is included there it should work out of the box in 1.4.1

A.

**Comment by asgothian** [comment]
It seems that there is no work done on this device on the zigbee-herdsman-converters side. Without this we cannot support the device. Unfortunately, device integration in the zigbee-herdsman-converters is near impossible without access to the device itself unless a similar device was previously implemented.

### Option 1:
You try to generate a log with detailed information on the device. An analysis of this log may lead to a 'similar' device which can then be used as a base implementation to get the device working. In order to do this, you need to:
- enable zigbee herdsman debug infos in the adapter configuration
- set the adapter to debug
- pair the device. Note down the _ieee Address_ from the device tile, as well as the information on _input clusters_ and _output clusters_ 
- attempt to operate the device to generate Status notifications. Make a note on each action taken (Exact time, action, result)
- using the "developer" tab in the zigbee adapter configuration, attempt to read attributes from the listed _input clusters_ and _output clusters_. Note down which read attempt provided which result.
- set the adapter back to info (without this step, the adapter can generate upwards of 2 GB log information every day)
- download the log
- Filter the log for the _ieee Address_ noted down earlier. All log entries which do not include this information should be discarded.
- Using the notes on your actions, cross reference actions taken with sections of the log (if any)

If you post this log file, it can be analysed to see if a similar device is known.


### Option 2:
You try your hand at supporting the device. yourself. It is not as hard as it may seem. The initial steps are the same as in Option 1.

With the log setup and information from that, you can attempt to follow[ these instructions](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) to get the device supported in the zigbee-herdsman-converters.

Once this is done and as long as the definition includes a number of expose entries, the device should show up as controllable in ioBroker. Note that no image will be generated for the device at this time.

### Option 3: 
Provide access to the device to a developer to do the implementation for you. Note that you may need to find someone to do this with you first.

There is a fourth option - sit back and wait.

A.

**Comment by asgothian** [comment]
Closed - there seems to be no further interest.

**Comment by Jean-GO** [comment]
Hello asgothian, can I send you a door handle (VisorTech NX6407) to integrate it into the Zigbee adapter?
If so, where can I send the door handle and return it to me when everything is ready?
Greetings Jean

**Comment by asgothian** [comment]
I am afraid that this will not work for the time being. I am swamped with far too many issues to handle until mid July at least, possibly longer. 

As it is a TuYa device with no known templates, i would estimate 10 to 20 hrs work for a basic implementation (open, close, status) but excluding the fingerprint functionality, as this is hidden in the manufactuerspecific tuya cluster without any documentation. Adding that will easily add another 20 to 40 hrs with sniffing network protocols and similar.

What you can do is to see if you can get any kind of documentation on the serial / zigbee interface from the manufacturer of the device.

A.

**Comment by Jean-GO** [comment]
I would still like to send them the door handle, I can wait 6 weeks or if it gets longer, it's not that bad either. But only if you want it.

**Comment by Jean-GO** [comment]
You can send me your address where I should send the package with the door handle.
With kind regards
Jean
my eMail: jeanpirch@aol.com

**Comment by Jean-GO** [comment]
Hola, todavía no he recibido ninguna noticia.
Con saludos cordiales
Jean

**Comment by Jean-GO** [comment]
Hello, when can I send the door handle to you. 
With kind regards
Jean

**Comment by Jean-GO** [comment]
Hello, when can I send you the door handle.
Thank you for a reply.
With kind regards
Jean

**Comment by Jean-GO** [comment]
Hi, PLEASE report
