### ISSUE TITLE
Please add Support for LXX60-CS27LX1.0 Curtain switch

### ISSUE THREAD

**Issue by caradas** [ioBroker/ioBroker.zigbee#920]
What information do you need?

>    modelZigbee:LXX60-CS27LX1.0
>     type:Router
>     nwk:26223
>     manuf id:4098
>     manufacturer:3A Smart Home DE
>     power:Unknown
>     hard version:0
>     zcl version:3
>     interviewed:true
>     configured:false
> 
>     endpoint:1
>     profile:260
>     input clusters:genBasic (0)
>     genIdentify (3)
>     genGroups (4)
>     genScenes (5)
>     genOnOff (6)
>     closuresWindowCovering (258)
>     output clusters:genIdentify (3)

bought from amazon probably these Bought from amazon probably these: https://www.amazon.de/-/en/Yagusmart-Zigbee-Curtain-Breaker-Control/dp/B08BFL1HDN

**Comment by asgothian** [comment]
- did you check if this one is listed as supported on zigbee2mqtt ?
- did you install v. 1.4.1 to see if it i supported ?

A.

**Comment by caradas** [comment]
I updated to git and they still have no functions
there aren't not listed on zigbee2mqtt but https://www.zigbee2mqtt.io/devices/LXN59-2S7LX1.0.html is, this one is basically the same design wise but probably lacks the interlocked output

**Comment by asgothian** [comment]
I checked the documentation, but was unable to complete integration. The assumption that it is identical to the listed device seems wrong - the number of endpoints does not seem to match.

In order to integrate this device, access to the device itself is necessary. I can only suggest that you either request device implementation at the zigbee-herdsman-converters project
or use [this documentation](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) to attempt device integration yourself.

**Comment by asgothian** [comment]
closed due to inactivity
