### ISSUE TITLE
Unable to use tint LED-Globeform white+color

### ISSUE THREAD

**Issue by D3rPap55t** [ioBroker/ioBroker.zigbee#924]
Hello,

I´m trying to switch from my Conbee II to CC1352P-2. Nearly all off my lights works fine.
I only got a problem with these lights tint LED-Globeform white+color.
https://www.mueller-licht.de/produktinformationen/artikel/404036/

I got following paring messages:
![zigbee](https://user-images.githubusercontent.com/73795363/103484277-d5884e80-4ded-11eb-9f3d-190591ed3a7c.PNG)

I know that this device is not supported. Is there a way to add a support?

Greetings

**Comment by asgothian** [comment]
Which adapter version do you have installed (check the log from adapter startup - it reports the version)

**Comment by D3rPap55t** [comment]
zigbee.0 | 2021-01-03 20:41:21.465 | info | (27462) starting. Version 1.4.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.19.0, js-controller: 3.1.6
-- | -- | -- | --

**Comment by D3rPap55t** [comment]
I hope this information can help you.

**Comment by asgothian** [comment]
In order to get this bulb working it needs to be implemented in the zigbee-herdsman-converters library. This requires an issue at [this](https://github.com/Koenkk/zigbee-herdsman-converters) project. The information needed for this issue is available on the tile for the bulb in the device list and the dialog which is displayed when the i icon is pressed on said tile.

A.

**Comment by D3rPap55t** [comment]
I have opend a new issuse at your link. Thanks for your help.

**Comment by asgothian** [comment]
Device is present in the latest zigbee-herdsman-converters.
