### ISSUE TITLE
Error when sending a command if the device cannot be reached

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#944]
The adapter sends commands even though the device cannot be reached. An error occurs.
This should actually be prevented ?!

`zigbee.0 | 2021-01-21 13:02:00.296 | error | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
-- | -- | -- | --
zigbee.0 | 2021-01-21 13:02:00.296 | error | at Generator.next (<anonymous>)
zigbee.0 | 2021-01-21 13:02:00.296 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:339:27)
zigbee.0 | 2021-01-21 13:02:00.296 | error | (16941) Error on send command to 0x00158d000448b30d. Error: Error: Command 0x00158d000448b30d/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":4}, {"timeout":10000,"disableResponse":false`

**Comment by asgothian** [comment]
This cannot be prevented. The available state is inconclusive, so the adapter will attempt to post a message to the device to control it. Pushing through messages to determine if a device is available for communication before actually sending the command is counter productive - some devices will accept a command but not respond. These devices would then be impossible to control. Suppressing some of the errors might be an option, but:

the error message you posted is incomplete. Most importantly, the cause of the error is cut from the message, since you copied it from the iobroker admin. When posting messages, you always have to post  messages from a downloaded log.

A.

**Comment by asgothian** [comment]
Please test my current fork of the adapter for a modification of the messages.

https://github.com/asgothian/ioBroker.zigbee

Note that the messages will remain as they are needed in order to give an indication that things are not as they should be.

A.

**Comment by asgothian** [comment]
Closed due to lack of interest in testing.
