### ISSUE TITLE
Irritiating signal display

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#980]
I wonder .. is it normal that all tiles show the exact same signal strenght (173)?

![grafik](https://user-images.githubusercontent.com/4311558/107474520-c3c76300-6b72-11eb-894d-1a7b8252785d.png)

**Comment by asgothian** [comment]
This is indeed odd. Please verify if the states "link Quality" all show this value too.

A.

**Comment by daniel-lo** [comment]
Yes .. the ojects show identical values.
I believe I must add that I use Conbee II with this adapter.

**Comment by easybeat** [comment]
I have a question about signal quality on tiles and on network map. They show completly different values:
![image](https://user-images.githubusercontent.com/37217887/111914826-f28b0000-8a73-11eb-8d80-03a035a905f7.png)

Map values:
![image](https://user-images.githubusercontent.com/37217887/111914845-08002a00-8a74-11eb-9a96-abd5ddba653e.png)

which ones are right?

**Comment by asgothian** [comment]
There is no easy answer to this question. Most likely, neither are "correct"

Here is why:

In order to obtain the map, each "router" device, i.e. each device with a constant supply of energy (in your case the Ikea router and the GU10 lightbulb) are asked for their link quality and their routing table. Within the routing table they list which devices are currently supposed to communicate through them and which was the link quality they have recorded for these devices. Note that this link quality is just the quality of the connection between the device and the router.

The link quality printed in the object list is the value taken from the link quality messages received from the device. I am not certain how the device records this value, but it has to take into account that the link to the coordinator is not necessarily as good as the link to the nearest router.

if you look at your map and device list, you will notice that the 5 end devices communication via the E1746 have high link qualities to the router. Looking at your object list, you can also see that the router itself has a very low link quality itself, indicating that the link from the end device to the coordinator may not be as good as seen in the map.

I hope this explanation makes sense.

One final note: the Link Quality for the Thermostat (10) is most likely an indication that the coordinator has not received a "link quality" message from the device since start of the adapter, as it is the default value set for any device at adapter start.

A.

**Comment by easybeat** [comment]
Hi

thank you very much. This is very interesting and I know understand to check all the link quality values.

The Thermostat has now recovered and his link quality is 48! And I will try and move the E1746 today to get a better link quality to the coordinator.

And in general a big Thank you to your team for this great adapter! Works really nice!

Cheers
