### ISSUE TITLE
ikea tradfr dimmer/switch E1743: missing battery indicator

### ISSUE THREAD

**Issue by klassisch** [ioBroker/ioBroker.zigbee#989]
According description in [E1743](https://www.zigbee2mqtt.io/devices/E1743.html) the device ikea tradri dimmer / switch E1743 schould expose battery state "Remaining battery in %. Value can be found in the published state on the battery property."
In the adapter version 1.4.2 this value is not visible as can be seen in the screen shot:
![grafik](https://user-images.githubusercontent.com/35134055/107876758-2b114a00-6ec8-11eb-9924-6181c127a8d4.png)

**Comment by asgothian** [comment]
This seems to be a known issue with the Ikea dimmer switches. Some just don't report their battery status.

If you want, you can try to catch the messages for this device for a day or two to verify if this one does send any battery information. In order to do that, you need to:

- install my current test version (from here: https://github.com/asgothian/ioBroker.zigbee)
- enter the IEEE address into the (then new)  _info.debugmessages_ state
- check the log for "warn" level messages from the zigbee adapter. I expect messages similar to his one `2021-02-14 11:44:43.030  - warn: zigbee.0 (7013) ELEVATED publishToState: message received ` to appear whenever the dimmer  sends a message to the coordinator.
- Let this run for **at least** 48 hrs, as some most battery driven devices send their battery status rarely to conserve battery.
A.

**Comment by asgothian** [comment]
Note that this feature is also available in the current GitHub version of the adapter, not just in my fork.

A.

**Comment by klassisch** [comment]
Thanks, I indeed startet the test with your fork, but got different trouble and too many changes in the network. So I had to move to the V1.4.4 and relocate the transceiver. Currently too many changes, so my log is not consistently and not really significantly. 
I will come back on this topic when my network will be stabilized and the expansion in more conservative state. 
But it is more about weeks than days.
