### ISSUE TITLE
Feature Request: device summary, disconnected devices, button for pairing

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.zigbee#991]
Hi,
I'm new with this great adapter, and I would like to have some features in the next versions, if possible to implement:
1) device summary ( object as number )
2) devices disconnected ( object as string, so that it is easy to send in telegram, or in a view )
3)  object button to start the pairing  ( I have around 130 devices, first 60 are paired, but I need a laptop to start the pairing.. with a button object I can easaly start this process per view, telegram etc.. )
4) and a object there is the last paired device written, so that I can see, if the pairing was successful.. 

Or if somebody have another ideas for this.. tell it me, please

**Comment by asgothian** [comment]
Similar to Issue #930

**Comment by asgothian** [comment]
My thoughts on the requested enhancements in Detail:
- device summary ( object as number ): 

What should be placed in this State, and why ? I see no reason / need for such a state.

- devices disconnected ( object as string, so that it is easy to send in telegram, or in a view ) :

Limited use. We could place the IEEE Address of each device which is set offline into a string, but this holds little to no information for a view or telegram message. The same is true for a device name. In the end, this functionality would provide limited added information, especially as it is quite simple to use a selector to generate said list with a script with exactly the information wanted for sending / displaying. 

- object button to start the pairing: 

I consider this a security risk. Pairing should be done in rare occasions only. If a larger number of devices need to be paired in one go, the pairing time can be extended as far as desired. While the text hints at a limit of 0 to 255 seconds for pairing, the number is not actually checked, so the network can be opened for an almost indefinite time by entering a large number. Exposing pairing via a state will invite people to try and automate reconnect attempts for their lost devices which is bound to fail.

- and a object there is the last paired device written, so that I can see, if the pairing was successful..

A state with the last pairing message is already available. It is possible to put this into a vis, or parse it to send a telegram message when a device was paired.

Please do not misunderstand me. If someone would like to spend time on implementing items 1,2 and 4 that is fine. I have too many other things on my list to deal with these. As far as item 3 is concerned - i am actively against implementation.

**Comment by Ilovegym66** [comment]
Hi, thank you for the detailed answer! 
I've migrated from 9 xiaomi gateways to one ( and a spare one ) CC26XR2, was installed in 30 minutes, and the first 50 devices are paired, in summary I have around 140-150 devices ( my last count was a year ago.. ) and I want to have now a fix count with all paired devices. :-) If I lost some, so I see this with the number of connected-disconnected devices.
Or I write a script, that check the avaible status ..   it's for me done in some minutes.. make no big issue of this, please.

Ok, that's fine, if I can setup the pairing time it's fine. Clear, this is only if you connect new devices, and than for security it have to set off.

Object with last pairing message I have found, fine!

No, everything is fine, you make a great job! Thanks in advance!
I close this issue, because everything is fine for me. The number of devices I have found in the log if the adapter start.
